oqtane/oqtane.framework

.gitignore

Add initial .gitignore file

---

Oqtane.Client/Modules/Admin/Login/Index.razor
Oqtane.Client/Modules/Admin/ModuleSettings/Index.razor
Oqtane.Client/Modules/Admin/Pages/Add.razor
Oqtane.Client/Modules/Admin/Pages/Delete.razor
Oqtane.Client/Modules/Admin/Pages/Edit.razor
Oqtane.Client/Modules/Admin/Pages/Index.razor
Oqtane.Client/Modules/Admin/Register/Index.razor
Oqtane.Client/Modules/Admin/Sites/Add.razor
Oqtane.Client/Modules/Controls/ActionLink.razor
Oqtane.Client/Modules/HtmlText/Edit.razor

Adjustment to ActionLink component to support custom button classes.  Adjustment of all button styles inside of the project to swap to either btn-danger for delete operations or btn-secondary for cancel operations for consistency.
Resolves #12

ActionLink Improvements

---

Oqtane.Client/Themes/Theme1/Container1.razor
Oqtane.Client/Themes/Theme1/Theme1.razor

General UI Cleanup.
* Widened the layout to be a fluid layout
* Adjusted padding on container & Content better fill pages
Resolves #14

Theme 1 Cleanup

---

Oqtane.Client/Themes/Theme1/Container1.razor
Oqtane.Client/Themes/Theme1/Theme1.razor

Reverts oqtane/oqtane.framework#15

Revert "Theme 1 Cleanup"

---

Oqtane.Client/Shared/Pane.razor
Oqtane.Client/Themes/Controls/ModuleTitle.razor

Fix module settings issue

---

Oqtane.Server/Startup.cs

Register new services in DI container

Client-side Blazor fix

---

Oqtane.Client/Modules/Admin/Pages/Add.razor
Oqtane.Client/Modules/Admin/Sites/Add.razor
Oqtane.Client/Services/ITenantService.cs
Oqtane.Client/Services/TenantService.cs
Oqtane.Client/Shared/Container.razor
Oqtane.Client/Shared/Pane.razor
Oqtane.Client/Shared/SiteRouter.razor
Oqtane.Client/Themes/Controls/Logo.razor
Oqtane.Server/Controllers/AliasController.cs
Oqtane.Server/Properties/launchSettings.json

added ability to add site through admin UI, fixed Logo control to not render if site does not have a logo, updated launchsettings so that port number is consistent for both IIS Express and .NET Core web server

add site admin, logo control, port number

---

Oqtane.Client/Modules/Admin/Login/Index.razor
Oqtane.Client/Shared/SiteRouter.razor
Oqtane.Client/Themes/Controls/Login.razor

Fixed issue where page was not reloaded after login/logout

Reload after login/logout

---

Oqtane.Client/Themes/Controls/Menu.razor

Refresh menu

---

README.md

Changed occurrences of ( this format ) to (this format).

Minor formatting change.

---

Oqtane.Client/Modules/Controls/Pager.razor

Is working, but I don't know if is the best solution.

Pager - Solution for the double click required to update the items

---

Oqtane.Server/Repository/ModuleRepository.cs
Oqtane.Server/Repository/PageRepository.cs

Fix UpdatePermissions instead of DeletePermissions in DeletePage and DeleteModule
Improve Page Delete to remove even modules, permissiones and pagemodules

Fix and Improve DeletePage

---

Oqtane.Client/Shared/ModuleInstance.razor
Oqtane.Client/Shared/Pane.razor
Oqtane.Client/Themes/Controls/ModuleActions.razor
Oqtane.Server/Controllers/ModuleController.cs
Oqtane.Server/Scripts/00.00.00.sql
Oqtane.Shared/Models/Module.cs
Oqtane.Shared/Models/PageModule.cs

Enable and Disable Page Module for SoftDelete.
In Page Edit Mode show gray (css) background if disabled.

Page module deletable

---

Oqtane.Client/Themes/Controls/ControlPanel.razor

Some minor fixes. 
Even "Select Page" should be reset to default value?

Content panel fix

---

Oqtane.Client/Modules/Admin/RecycleBin/Index.razor
Oqtane.Client/Themes/Controls/ControlPanel.razor
Oqtane.Client/Themes/Controls/TabControl.razor
Oqtane.Client/Themes/Controls/TabPage.razor
Oqtane.Client/Themes/Controls/TabPanel.razor
Oqtane.Server/Repository/PageRepository.cs
Oqtane.Shared/Models/Module.cs

this should complete the #105 with the expected behavior

Improved recycle bin

---

Oqtane.Server/Infrastructure/LogManager.cs

I've found it when I try to add a page with null parent

fix for logmanager nullexception when values is null

---

Oqtane.Server/Extensions/AssemblyExtensions.cs
Oqtane.Server/Extensions/OqtaneMvcBuilderExtensions.cs
Oqtane.Server/Extensions/OqtaneServiceCollectionExtensions.cs
Oqtane.Server/Modules/MVCModuleExtension.cs
Oqtane.Server/Startup.cs

This include:
- Add Oqtane `ServiceCollection` extension methods such as: `AddOqtaneModules()`, `AddOqtaneThemes()` .. etc
- Add missing theme types to the modules assemblies

Oqtane service collection extensions

---

Oqtane.Client/Modules/Admin/Sites/Edit.razor
Oqtane.Client/Shared/ModuleInstance.razor
Oqtane.Client/Shared/SiteRouter.razor

My first pull request, i'm learning how to collaborate :)

Missing nullchecks -> unhandled exceptions

---

Oqtane.Client/Themes/Controls/ControlPanel.razor
Oqtane.Server/appsettings.json

Check if moduledefinitionname has valid value

Add Module Value Check

---

Oqtane.Client/Modules/Admin/Sites/Index.razor
Oqtane.Client/Modules/Controls/ActionDialog.razor
Oqtane.Client/Modules/Controls/ActionLink.razor
Oqtane.Server/Controllers/SiteController.cs
Oqtane.Server/Repository/SiteRepository.cs

Unable to deleted the root site

---

Oqtane.Client/Modules/Admin/Files/Edit.razor

folderid is not initialized - folder cannot be created

Folder creation fail

---

Oqtane.Client/Modules/ModuleBase.cs

Fix of #252 and some cosmetics

ModuleBase fix

---

Oqtane.Client/Modules/Controls/ModuleMessage.razor

Naming fix

---

Oqtane.Test/Oqtane.Test.csproj
Oqtane.sln

Fixes #230
Just adding an empty unit test project with the required dependencies, hopefully if we can add unit tests for the entire platform as well as for the bugs that we fixed if it's possible

Add unit test project

---

Oqtane.Client/Oqtane.Client.csproj
Oqtane.Server/Oqtane.Server.csproj
Oqtane.Shared/Oqtane.Shared.csproj

To avoid warning "Namespace does not correspond to file location"

Changed root namespace in project to reflect namespaces in files

---

Oqtane.Client/Modules/Admin/Dashboard/Index.razor
Oqtane.Client/Modules/Admin/Files/Edit.razor
Oqtane.Client/Modules/Admin/ModuleDefinitions/Edit.razor
Oqtane.Client/Modules/Admin/Pages/Add.razor
Oqtane.Client/Modules/Admin/Sites/Edit.razor
Oqtane.Client/Modules/Admin/UserProfile/Index.razor
Oqtane.Client/Modules/Admin/Users/Add.razor
Oqtane.Client/Modules/Admin/Users/Edit.razor
Oqtane.Client/Modules/Controls/ActionDialog.razor
Oqtane.Client/Modules/Controls/ActionLink.razor
Oqtane.Client/Modules/Controls/FileManager.razor
Oqtane.Client/Themes/Controls/ControlPanel.razor
Oqtane.Client/Themes/Controls/Menu.razor
Oqtane.Client/Themes/Controls/ModuleActions.razor
Oqtane.Client/UI/Pane.razor
Oqtane.Client/UI/SiteRouter.razor
Oqtane.Server/Controllers/FileController.cs
Oqtane.Server/Controllers/FolderController.cs
Oqtane.Server/Controllers/ModuleController.cs
Oqtane.Server/Controllers/ModuleDefinitionController.cs
Oqtane.Server/Controllers/PageController.cs
Oqtane.Server/Controllers/PageModuleController.cs
Oqtane.Server/Controllers/SettingController.cs
Oqtane.Server/Startup.cs
Oqtane.Shared/Shared/PermissionNames.cs
Oqtane.Test/Oqtane.Test.csproj

Replace magic strings in authorization calls

PermissionNames constants

---

Oqtane.Client/Modules/Admin/Files/Edit.razor
Oqtane.Client/Modules/Admin/ModuleDefinitions/Edit.razor
Oqtane.Server/Controllers/FileController.cs
Oqtane.Server/Controllers/FolderController.cs
Oqtane.Server/Controllers/ModuleController.cs
Oqtane.Server/Controllers/PageController.cs
Oqtane.Server/Controllers/PageModuleController.cs
Oqtane.Server/Controllers/SettingController.cs
Oqtane.Server/Controllers/SiteController.cs
Oqtane.Server/Controllers/UserController.cs
Oqtane.Server/Controllers/UserRoleController.cs
Oqtane.Shared/Shared/EntityNames.cs

Magic strings ii

---

Oqtane.Server/Repository/SiteRepository.cs

Not necessary to build default pages in constructor.

Site repository refactoring

---

Oqtane.Client/Modules/Controls/ActionLink.razor

UI improvement to be able to add icons to the Action Links.
Code Use (after):
```
<ActionLink Action="Add" EditMode="false" IconName="plus" Text="Add Something" />
<ActionLink Action="Edit" EditMode="false" IconName="pencil" Text="Edit Something" />
```
Code Use (before):
```
<ActionLink Action="Add" EditMode="false" Text="Add Something" />
<ActionLink Action="Edit" EditMode="false" Text="Edit Something" />
```
Results

Added functionality to add icons to the ActionLinks.

---

Oqtane.Client/Modules/Admin/Register/Index.razor
Oqtane.Shared/Shared/Utilities.cs

Use a regex to check if an email is valid.

Check for a valid email.

---

Oqtane.Client/Modules/Admin/Tenants/Edit.razor
Oqtane.Client/Modules/Admin/Tenants/Index.razor
Oqtane.Server/Repository/TenantRepository.cs
Oqtane.Shared/Shared/Constants.cs

Prevent deleting master tenant

---

Oqtane.Server/Infrastructure/DatabaseManager.cs
Oqtane.Server/Repository/TenantRepository.cs

Tenant repository bug

---

Oqtane.Client/Services/AliasService.cs
Oqtane.Client/Services/FileService.cs
Oqtane.Client/Services/FolderService.cs
Oqtane.Client/Services/InstallationService.cs
Oqtane.Client/Services/JobLogService.cs
Oqtane.Client/Services/JobService.cs
Oqtane.Client/Services/LogService.cs
Oqtane.Client/Services/ModuleDefinitionService.cs
Oqtane.Client/Services/ModuleService.cs
Oqtane.Client/Services/NotificationService.cs
Oqtane.Client/Services/PackageService.cs
Oqtane.Client/Services/PageModuleService.cs
Oqtane.Client/Services/PageService.cs
Oqtane.Client/Services/ProfileService.cs
Oqtane.Client/Services/RoleService.cs
Oqtane.Client/Services/ServiceBase.cs
Oqtane.Client/Services/SettingService.cs
Oqtane.Client/Services/SiteService.cs
Oqtane.Client/Services/TenantService.cs
Oqtane.Client/Services/ThemeService.cs
Oqtane.Client/Services/UserRoleService.cs
Oqtane.Client/Services/UserService.cs

Use string Interpolation for constructing Urls

---

Oqtane.Client/Modules/Admin/Pages/Add.razor
Oqtane.Client/Modules/Admin/Pages/Edit.razor
Oqtane.Client/Modules/Admin/Site/Index.razor
Oqtane.Client/Modules/Admin/Sites/Add.razor
Oqtane.Client/Modules/Admin/Sites/Edit.razor

Fixes #330 which is address `string.Empty` regression bugs that was occurs from #314

Fix regression bugs

---

Oqtane.Server/Infrastructure/InstallationManager.cs
Oqtane.Server/Startup.cs

"Calling 'BuildServiceProvider' from application code results in an additional copy of singleton services being created. Consider alternatives such as dependency injecting services as parameters to 'Configure'"

Solution of warning about additional singleton of InstallManager

---

Oqtane.Client/Modules/Admin/Register/Index.razor
Oqtane.Client/Services/UserService.cs

This just hides the UI if the site does not allow registration.  I will get the controller later. You can wait until I add that, or accept this as-is.

Fix register

---

Oqtane.Client/Services/ServiceBase.cs
Oqtane.Client/Services/UserService.cs

- some cosmetics, code is reordered in servicebase.cs,  
- minor bugs in state checking,
- logging preparation,
- error checking
- Fixed bug with site.AllowRegistration in case of installation

Migration to using System.Net.Http.Json; part two

---

Oqtane.Client/Modules/HtmlText/Index.razor

Fix #396, may be I can fix this later using css

Render line break conditionally in HtmlText module

---

Oqtane.Server/Infrastructure/DatabaseManager.cs

Create Data directoty if does not exists

---

Oqtane.Client/Themes/Controls/Login.razor
Oqtane.Client/Themes/Controls/LoginBase.cs
Oqtane.Client/Themes/Controls/Menu.razor
Oqtane.Client/Themes/Controls/MenuBase.cs
Oqtane.Client/Themes/Controls/MenuHorizontal.Razor
Oqtane.Client/Themes/Controls/MenuVertical.razor

Login component refactoring
Code moved to base class for easy overriding in custom themes.

Menu component refactoring

---

Oqtane.Client/UI/Installer.razor
Oqtane.Server/Controllers/InstallationController.cs
Oqtane.Server/Infrastructure/DatabaseManager.cs

Get custom theme and layout on a default install

---

Oqtane.Client/Modules/Admin/SystemInfo/Index.razor

System Info input disabled changed to readonly to allow copy and paste

System Info input disabled changed to readonly

---

Oqtane.Client/UI/Pane.razor

resolves issue with title border DIV not utilizing 100% pane size

container class added to pane

---

Oqtane.Server/Controllers/FileController.cs

File Download crash when image does not exist

File Controller bug

---

Oqtane.Client/Modules/Admin/Files/Add.razor
Oqtane.Client/Modules/Admin/ModuleDefinitions/Add.razor
Oqtane.Client/Modules/Admin/Site/Index.razor
Oqtane.Client/Modules/Admin/Themes/Add.razor
Oqtane.Client/Modules/Admin/UserProfile/Index.razor
Oqtane.Client/Modules/Admin/Users/Edit.razor
Oqtane.Client/Modules/Controls/FileManager.razor

File Manager
* Added possibility to hide folder selection and upload part to allow user only select from uploaded images or only to specified folder
* Change parameters type from string to corresponding type
~~Control Panel~~
~~* Values are not cleared when add module is pressed~~
~~* last used category is stored to options~~
~~Settings~~
~~* `public Setting Get(string entityname, int entityid, string settingName)` added possibility to query only one value by name~~

FileManager Tune-Up

---

Oqtane.Client/Services/SettingService.cs

Setting service bug.

---

Oqtane.Client/Modules/Admin/Files/Add.razor
Oqtane.Server/Controllers/FileController.cs

Apply file name validation rules to the File Controller and client.

Add File Name validation

---

Oqtane.Client/Modules/Admin/ModuleCreator/Templates/External/Server/[Owner].[Module]s.Server.csproj

Added 's' to the module creator SQL script in the csproj to fix compilation error.

Fix module pluralization

---

Oqtane.Client/Modules/Admin/ModuleCreator/Templates/External/Client/[Owner].[Module]s.Client.csproj
Oqtane.Client/Modules/Admin/ModuleCreator/Templates/External/Server/[Owner].[Module]s.Server.csproj

This updates the references for the external module.

External module creator refs

---

Oqtane.Server/wwwroot/Themes/Oqtane.Themes.OqtaneTheme/Theme.css

Oqtane Theme:  CSS style module actions dropdown text #fff

---

Oqtane.Server/Controllers/AliasController.cs

Added wildcard route catchall resolves #546

Fix Alias name route

---

Oqtane.Shared/Shared/Utilities.cs

- safe way to check if key is presented
- safe parsing int values in query
- should replace int.Parse() when reading query string
for example
`_jobId = Int32.Parse(PageState.QueryString["id"]);`
can throw unhanded exception when "id" is not int
correct way
`  if (PageState.Uri.TryGetQueryValueInt("id",out _jobId)) ....`

Uri extensions for read query values

---

Oqtane.Client/Themes/Controls/MenuHorizontal.Razor

use same logic as in vertical menu

Horizontal menu fix

---

Oqtane.Client/Themes/ContainerBase.cs
Oqtane.Client/Themes/LayoutBase.cs
Oqtane.Client/Themes/ThemeBase.cs
Oqtane.Client/Themes/ThemeControlBase.cs
Oqtane.Server/Repository/ModuleDefinitionRepository.cs
Oqtane.Server/Repository/ThemeRepository.cs
Oqtane.Shared/Extensions/AssemblyExtensions.cs

To avoid false detection of base types

OqtaneIgnore implementation fix

---

Oqtane.Client/Modules/Admin/UserProfile/Index.razor

fixes #539
Part 1 of 2 #586,  
This PR is similar to #540 which should not be merged, instead use these two as they have broken down the changes into two PR.
- Issue:  Removes Infinite RE: in reply messages
- Issue:  Removes reply from message
- Enhancement:  Adds "..." to messages longer than 100
- Enhancement:  Removes carriage returns from messages
This PR is similar to #540 which should not be merged, instead use these two as they have broken down the changes into two PR.
-  Grouping messages that are replies with a sort feature "by conversation" so they don't all show up from a user .  A better UX to keep up with other users and things going on can help keep the amount of redundant information from being display using a way people are familiar with today.

'...' added, Reply Removed

---

Oqtane.Client/Modules/Controls/ActionLink.razor
Oqtane.Client/UI/SiteRouter.razor
Oqtane.Server/Controllers/UserController.cs

+ siterouter nullchecking.
+ actionlink space fix
+ lovercase username in filter

small fixes

---

Oqtane.Client/Services/ThemeService.cs

Fixed ThemeService using tenant aware api calls

---

Oqtane.Client/Modules/ModuleBase.cs
Oqtane.Client/UI/PageState.cs
Oqtane.Client/UI/SiteRouter.razor
Oqtane.Server/appsettings.json
Oqtane.Shared/Shared/Constants.cs
Oqtane.Shared/Shared/Utilities.cs

Allows for PageVariables through the URL. This should not change the current functionality of module routing, it just allows for you to get variables through the URL.
Example: 
```
public override string Actions { get { return "AddBlog,
EditBlog/[blogId],
EditBlog/[blogId]/EditChildBlog/[childBlogId]]"; } }

Module Router Enhancement

---

Oqtane.Client/UI/SiteRouter.razor

fixes the issue with not being able to use modules on the homepage due to #638

Hot fix for Homepage and Admin module routing

---

Oqtane.Server/Repository/NotificationRepository.cs

I wondered why my users complains than messages had not been delivered.

Notification Repository Breaking change fix

---

Oqtane.Client/Themes/Controls/ModuleActions.razor
Oqtane.Client/Themes/Controls/ModuleActionsBase.cs

Icons in module actions menu

---

Oqtane.Server/Infrastructure/Jobs/NotificationJob.cs

Just undo of #643, Mistake in analysis, sorry.

Notification changes UNDO

---

Oqtane.Server/Infrastructure/InstallationManager.cs

This PR resolves two issues I have found adding external modules to oqtane:
1. If the nuget of an added external module contains dll files that already in use an exception was thrown that this file couldn't be accessed. Now the file accessibility is checked before the file is extracted.
2. If a third party tool depends on native runtime dlls (e.g. sqlite) than these runtime-dlls have to be added into a special runtime directory within the bin folder. Now the implementation is extended to also correctly extract this runtime directory from the nuget package of the external module.

Fixes 2 external module installation problems

---

Oqtane.Server/Extensions/OqtaneServiceCollectionExtensions.cs
Oqtane.Server/Startup.cs

Now I'm happy to avoid building service provider manually
/cc @sbwalker

Avoid Building ServiceProvider in ConfigureServices

---

Oqtane.Shared/Documentation/InternalApi.cs
Oqtane.Shared/Documentation/PrivateApi.cs
Oqtane.Shared/Documentation/PublicApi.cs
Oqtane.Shared/Documentation/WorkInProgressApi.cs
Oqtane.Shared/Documentation/readme.md

part of https://github.com/oqtane/oqtane.framework/issues/570

Add Documentation attributes #570

---

Oqtane.Client/Oqtane.Client.csproj
Oqtane.Server/wwwroot/Modules/Templates/External/Shared/[Owner].[Module].Shared.csproj
Oqtane.Shared/Oqtane.Shared.csproj
Oqtane.Test/Oqtane.Test.csproj
Oqtane.Upgrade/Oqtane.Upgrade.csproj

Addresses the comment https://github.com/oqtane/oqtane.framework/discussions/832#discussioncomment-105509

Remove LangVersion

---

Oqtane.Client/Modules/Controls/ActionLink.razor

Fix issue with ActionLink localization

---

Oqtane.Client/Modules/Controls/ActionDialog.razor

Localize ActionDialog

---

Oqtane.Client/Modules/Controls/TabPanel.razor
Oqtane.Client/Modules/Controls/TabStrip.razor

Localize TabPanel component

---

Oqtane.Client/Modules/Controls/Section.razor

Localize section component

---

Oqtane.Client/Oqtane.Client.csproj
Oqtane.Server/Oqtane.Server.csproj
Oqtane.Shared/Oqtane.Shared.csproj

Upgrade packages to .NET 5 RTM

---

Oqtane.Client/Modules/Controls/ActionDialog.razor
Oqtane.Client/Modules/Controls/Label.razor
Oqtane.Client/Modules/Controls/LocalizableComponent.cs
Oqtane.Client/Modules/Controls/Section.razor
Oqtane.Client/Modules/Controls/TabPanel.razor

This address my comment [here](https://github.com/oqtane/oqtane.framework/issues/890#issuecomment-729099319)

Fallback to English as default culture

---

Oqtane.Client/Modules/Controls/ActionLink.razor

Fix localization issue in ActionLink

---

Oqtane.Client/Oqtane.Client.csproj
Oqtane.Client/Program.cs
Oqtane.Client/Services/Interfaces/ILocalizationService.cs
Oqtane.Client/Services/LocalizationService.cs
Oqtane.Client/Themes/Controls/ControlPanel.razor
Oqtane.Client/Themes/Controls/LanguageSwitcher.razor
Oqtane.Client/UI/Interop.cs
Oqtane.Server/Controllers/LocalizationController.cs
Oqtane.Server/Extensions/ApplicationBuilderExtensions.cs
Oqtane.Server/Pages/_Host.cshtml
Oqtane.Server/Startup.cs
Oqtane.Server/wwwroot/js/interop.js
Oqtane.Shared/Models/Culture.cs

Add Language switcher

---

Oqtane.Server/Infrastructure/LogManager.cs

I revert the logs localization as you suggested @sbwalker, please merge this and we could think about it deeply later

Revert LogManager localization changes

---

Oqtane.Client/Modules/ModuleBase.cs
Oqtane.Server/Controllers/FileController.cs
Oqtane.Server/Extensions/MimeUtilities.cs
Oqtane.Server/Extensions/StringExtensions.cs
Oqtane.Shared/Shared/Utilities.cs

Add ability to direct content disposition of file
`api/file/download/{fileid}`  inline
`api/file/download/{fileid}/attach`  attachment

FileController - content disposition

---

Oqtane.Server/Controllers/FileController.cs
Oqtane.Server/Repository/FileRepository.cs
Oqtane.Server/Repository/FolderRepository.cs
Oqtane.Server/Repository/Interfaces/IFileRepository.cs
Oqtane.Server/Repository/Interfaces/IFolderRepository.cs

For simplify file manipulation in server modules.

Introduce GetFolderPath and GetFilePath repository methods

---

Oqtane.Client/Modules/Admin/Languages/Add.razor
Oqtane.Client/Modules/Admin/Languages/Index.razor
Oqtane.Client/Program.cs
Oqtane.Client/Services/Interfaces/ILanguageService.cs
Oqtane.Client/Services/LanguageService.cs
Oqtane.Client/Themes/Controls/LanguageSwitcher.razor
Oqtane.Server/Controllers/LanguageController.cs
Oqtane.Server/Repository/Context/TenantDBContext.cs
Oqtane.Server/Repository/Interfaces/ILanguageRepository.cs
Oqtane.Server/Repository/LanguageRepository.cs
Oqtane.Server/Repository/SiteRepository.cs
Oqtane.Server/Scripts/Tenant.02.00.02.00.sql
Oqtane.Server/Startup.cs
Oqtane.Shared/Models/Language.cs

Add Languages Management

---

Oqtane.Server/Oqtane.Server.csproj

Fixes #1108, still I can't remember why this is missing from the PR #834

Remove LangVerion from Oqtane.Server

---

Oqtane.Client/Modules/Admin/Site/Index.razor

The saved function for the favicon was not there

Fixed site Favicon not saving

---

Oqtane.Client/Modules/Admin/Files/Index.razor
Oqtane.Server/Controllers/FileController.cs

Reverts oqtane/oqtane.framework#1121

Revert "Fix Upload SVG throw error #1120"

---

Oqtane.Server/wwwroot/Modules/Templates/External/Server/[Owner].[Module].Server.csproj

LangVersion removed from External Server Template

Fix for #1148 LangVersion set to 7.3

---

Oqtane.Client/Modules/Admin/Profiles/Index.razor

Delete profile should refresh profiles list

---

Oqtane.Server/Controllers/UserController.cs
Oqtane.Server/Repository/FolderRepository.cs
Oqtane.Server/Repository/Interfaces/IFolderRepository.cs

fix: user delete

---

Oqtane.Client/Modules/Admin/ModuleDefinitions/Index.razor
Oqtane.Client/Modules/Admin/Pages/Index.razor
Oqtane.Client/Modules/Admin/Profiles/Index.razor
Oqtane.Client/Modules/Admin/RecycleBin/Index.razor

Address the issue in https://github.com/oqtane/oqtane.translations/issues/7#issuecomment-810413650

Fix localizer in Admin pages

---

Oqtane.Server/Infrastructure/LocalizationManager.cs

This PR is replacement of #1263 it includes:
- Add English to the supported cultures by default
- Order the cultures to be displayed in the switcher in the alphabatic order

LocalizationManager enhancements

---

Oqtane.Shared/Shared/Constants.cs

https://github.com/oqtane/oqtane.framework/issues/1283

Make version static-readonly

---

Oqtane.Database.MySQL/MySQLDatabase.cs
Oqtane.Database.PostgreSQL/PostgreSQLDatabase.cs
Oqtane.Database.SqlServer/LocalDbDatabase.cs
Oqtane.Database.SqlServer/SqlServerDatabase.cs
Oqtane.Database.Sqlite/SqliteDatabase.cs
Oqtane.Test/Oqtane.Database.MySQL/MySqlDatabaseTests.cs
Oqtane.Test/Oqtane.Database.PostgreSQL/PostgreSQLDatabaseTests.cs
Oqtane.Test/Oqtane.Database.SqlServer/LocalDbDatabaseTests.cs
Oqtane.Test/Oqtane.Database.SqlServer/SqlServerDatabaseTests.cs
Oqtane.Test/Oqtane.Database.Sqlite/SqliteDatabaseTests.cs
Oqtane.Test/Oqtane.Test.csproj

Database type name should use type AssemblyQualifiedName instead of magic string

---

Oqtane.Server/Migrations/02010002_ChangeFolderNameAndPathColumnsSize.cs
Oqtane.Server/Migrations/02020001_ChangeFolderNameAndPathColumnsSize.cs

Change Folder Name & Path length

---

Oqtane.Shared/Models/ConnectionStringField.cs
Oqtane.Shared/Models/Culture.cs
Oqtane.Shared/Models/Database.cs
Oqtane.Shared/Models/Installation.cs
Oqtane.Shared/Models/Job.cs
Oqtane.Shared/Models/JobLog.cs
Oqtane.Shared/Models/Language.cs
Oqtane.Shared/Models/ModuleContent.cs
Oqtane.Shared/Models/ModuleDefinition.cs
Oqtane.Shared/Models/Notification.cs
Oqtane.Shared/Models/Package.cs
Oqtane.Shared/Models/Permission.cs
Oqtane.Shared/Models/PermissionString.cs
Oqtane.Shared/Models/Profile.cs
Oqtane.Shared/Models/Resource.cs
Oqtane.Shared/Models/Theme.cs

https://github.com/oqtane/oqtane.framework/issues/1382
Should not contain any code changes, just docs

More documentation - almost all Models done #1382

---

Oqtane.Server/Migrations/Tenant/02010001_ChangeFolderNameAndPathColumnsSize.cs

This PRfixes the issue with Sqlite not installing correctly (Issue #1420)

Fix for Issue #1420

---

Oqtane.Server/Controllers/InstallationController.cs

for more information please go back to request #1460

fix issue: WebAssembly with IDM app

---

Oqtane.Client/Oqtane.Client.csproj
Oqtane.Client/Resources/SharedResources.cs
Oqtane.Client/SharedResources.cs

Namespace was changed from Oqtane to Oqtane.Client

SharedResources to reside at the project root.

---

Oqtane.Client/Program.cs
Oqtane.Test/Oqtane.Client.Tests/LocalizationCookieTests.cs
Oqtane.Test/Oqtane.Test.csproj

Fix parsing localization cookie when the value is not present

---

Oqtane.Databases.sln

I notice that Databases doesn't build becasue the fact `Oqtane.Server` was missing

Add missing Oqtane.Server into Databases solution

---

Oqtane.Client/SharedResources.cs
Oqtane.Client/Themes/Controls/Theme/ControlPanel.razor

Updated the ControlPanel to use Shared resources for local strings ;
**Add**, **Edit**, **Delete**, **Cancel**
Corrected the SharedResources.cs namespace.

Introduce SharedResource Localisation to ControlPanel

---

Oqtane.Client/Modules/Admin/Login/Index.razor
Oqtane.Server/Extensions/OqtaneMvcBuilderExtensions.cs

Allowed pages for the external modules.

Allowed pages for external modules.

---

Oqtane.Server/wwwroot/Modules/Templates/External/Client/Modules/[Owner].[Module]/Edit.razor
Oqtane.Server/wwwroot/Modules/Templates/External/Client/Modules/[Owner].[Module]/Settings.razor

replace tables in markup with responsive approach.

Modified External Module Template

---

Oqtane.Client/Modules/Admin/Jobs/Edit.razor
Oqtane.Client/Modules/Admin/Pages/Add.razor
Oqtane.Client/Modules/Admin/Pages/Edit.razor
Oqtane.Client/Modules/Admin/Themes/Add.razor
Oqtane.Client/Modules/Admin/UserProfile/Add.razor
Oqtane.Client/Modules/Admin/UserProfile/Index.razor
Oqtane.Client/Modules/Admin/UserProfile/View.razor
Oqtane.Client/Modules/Admin/Users/Edit.razor
Oqtane.Client/Modules/HtmlText/Settings.razor
Oqtane.Client/Themes/Controls/Theme/ControlPanel.razor
Oqtane.Client/Themes/OqtaneTheme/Containers/ContainerSettings.razor
Oqtane.Client/Themes/OqtaneTheme/Themes/ThemeSettings.razor

replace tables in markup with responsive approach

Modifications for Bootstrap 5

---

Oqtane.Server/wwwroot/Themes/Templates/External/Package/debug.cmd

Copy external Theme to Oqtane.Server.

---

README.md
azuredeploy.json

Addresses "Deploy to Azure" failing #1547

Removes writing database connection string to appsettings.json in AzureDeploy.json

---

Oqtane.Client/Modules/Admin/Login/Index.razor

Fixes #1579 Exception when browsing to /login when you are already logged in

---

Oqtane.Server/Migrations/EntityBuilders/BaseEntityBuilder.cs
Oqtane.Server/Migrations/Tenant/02020001_AddPageIsClickable.cs

String value doesn't work for bool type on PgSQL

EntityBuilder UpdateColumn to dynamic type of value

---

Oqtane.Server/Migrations/EntityBuilders/BaseEntityBuilder.cs
Oqtane.Server/Migrations/Tenant/02020001_AddPageIsClickable.cs

Reverts oqtane/oqtane.framework#1603

Revert "EntityBuilder UpdateColumn to dynamic type of value"

---

Oqtane.Client/Modules/Admin/Pages/Add.razor
Oqtane.Client/Resources/Modules/Admin/Pages/Add.resx

Validate if Page in Recycle Bin During Creation

---

Oqtane.Client/Modules/Admin/Users/Edit.razor

Profile properties as dropdown in User Management

---

Oqtane.Client/Modules/Controls/AuditInfo.razor

Added Parameter DateTimeFormat with default value of  "MMM dd yyyy HH:mm:ss"

Update for #1753 Date format for the Audit

---

Oqtane.Client/Modules/Admin/Pages/Index.razor
Oqtane.Client/Resources/Modules/Admin/Pages/Index.resx
Oqtane.Client/Resources/Modules/Admin/Site/Index.resx

Added Open button that will navigate to sub pages

Fix for #1749 navigate to sub sub pages

---

Oqtane.Client/Themes/BlazorTheme/Containers/Container.razor
Oqtane.Client/Themes/BlazorTheme/Themes/Default.razor
Oqtane.Server/wwwroot/Themes/Oqtane.Themes.BlazorTheme/Theme.css

Theme now renders and is fully responsive

Fix for #1736 Blazor theme not rendering correctly

---

Oqtane.Client/Modules/Admin/Pages/Index.razor

The correct path was returned but the navigation was not being executed.

Navigation

---

Oqtane.Client/Themes/Controls/Theme/MenuHorizontal.razor
Oqtane.Client/Themes/OqtaneTheme/Themes/Default.razor

Fixed issue with OffCanvas not rendering properly.

Upgrade to 5.1.3 Bootstrap and Bootswatch Cyborg

---

Oqtane.Client/Modules/Admin/Sites/Index.razor

replace * alias with uri.Authority in sites admin

Fix - site with default alias (*) edit fail

---

Oqtane.Client/Modules/Admin/Pages/Edit.razor
Oqtane.Client/Resources/Modules/Admin/Pages/Edit.resx
Oqtane.Client/Resources/SharedResources.resx

Add a new tabpane that lists all the module on that page.  From here you are able to modify the module settings and or delete the module from a page.  Delete will send the module to the recycle bin.

Modification to Page Management component 

---

Oqtane.Server/Startup.cs

Address https://github.com/oqtane/oqtane.framework/discussions/1817

Handle SchemaId in Swagger

---

Oqtane.Client/Modules/Controls/TabPanel.razor

Fix heading localization in TabPanel

---

Oqtane.Client/Modules/Controls/Pager.razor

Add the option "Both" to display the toolbar at the top and bottom of the pager.  Nice if the Pager is displaying large sets of data.

Update the ToolBar position on the Pager Component

---

Oqtane.Server/Migrations/Tenant/02030002_AddSettingIsPublic.cs

This should fix the error on installing with PostgreSQL.
I did not check oder database types.

Make IsPublic of type bool to make PostgreSQL happy

---

Oqtane.Server/Controllers/ModuleController.cs

Fixed the permissions validation and added functionality to remove all the settings for the deleted module.

1877 Module data not being delete when recycle bin is purged

---

Oqtane.Client/Modules/Admin/Users/Index.razor

Search user work again

---

Oqtane.Client/Modules/Admin/Login/Index.razor
Oqtane.Client/Resources/Modules/Admin/Login/Index.resx
Oqtane.Client/Resources/Modules/Admin/Visitors/Index.resx

Added missing Keys for Login and Visitor

Missing Resx Keys 

---

Oqtane.Client/Modules/Controls/Label.razor

Modified so that the Class parameter is not constantly appended when a new Class is applied.

Fix for  #1914 Label Control appending Class to LabelClass

---

Oqtane.Client/UI/ThemeBuilder.razor

Fixed the bug that CSS could not be render when the module was loaded for the first

Fixed first render css bug

---

Oqtane.Client/Resources/Modules/Admin/Pages/Edit.resx

Empty Resx Value on Page Edit

---

Oqtane.Client/Modules/Admin/Roles/Users.razor
Oqtane.Client/Modules/Admin/Users/Index.razor
Oqtane.Client/Resources/SharedResources.resx

When looking through Users and Roles it would seem ideal to also show the username.

Add the Username to the User And Roles display.

---

Oqtane.Client/Modules/Admin/ModuleDefinitions/Index.razor

added a '?' operator after the m.ModuleDefinition

null reference exception still occurring

---

Oqtane.Client/Modules/Admin/UserProfile/Add.razor

typo correction for closing tag

typo correction for closing tag

---

Oqtane.Server/Repository/ModuleRepository.cs

Added the module Settings so they are available for the Import and Export Interface.

Fix for Module Settings Import and Export #2019

---

Oqtane.Shared/Shared/Constants.cs

Udate to FileUpload Constant 
added extensions json, xml, xslt, rss, html, htm, css
This is an interim fix with plans to make the upload extensions a soft implementation.

Fix for File Upload Failed {Error} .json file #2052

---

Oqtane.Client/Modules/Admin/UserProfile/Index.razor
Oqtane.Client/Resources/Modules/Admin/UserProfile/Index.resx

Added button to delete all the notifications for the selected filter.

Allow the deletion of all Notifications

---

Oqtane.Client/Modules/Admin/UserProfile/Index.razor
Oqtane.Client/Modules/Admin/Users/Add.razor
Oqtane.Client/Modules/Admin/Users/Edit.razor
Oqtane.Client/Resources/Modules/Admin/UserProfile/Index.resx
Oqtane.Client/Resources/Modules/Admin/Users/Add.resx
Oqtane.Client/Resources/Modules/Admin/Users/Edit.resx

Updated the Components where the Password is required to allow toggle show / hide

User Areas to use the Toggle Password method

---

Oqtane.Client/Modules/Admin/ModuleDefinitions/Index.razor

provide newer/latest module package version (instead of already installed version) to download code

Fix #2160 - upgrade module option

---

Oqtane.Client/Modules/Admin/UserProfile/Index.razor

Updated the format to a more readable format of dd-MMM-yyyy

Updated the CreatedOn date format

---

Oqtane.Client/Modules/Admin/Users/Index.razor

The Display name and email address  not is the correct order!

Args not in sink

---

Oqtane.Client/Themes/Controls/Theme/MenuItemsHorizontal.razor
Oqtane.Client/Themes/Controls/Theme/MenuItemsVertical.razor

Solves the issue https://github.com/oqtane/oqtane.framework/issues/2175

* Collapse menu after click on a page (mobile version)

---

Oqtane.Client/Modules/Admin/Logs/Index.razor
Oqtane.Server/Infrastructure/LogManager.cs

Recently my inbox is spammed with messages like:
Subject: Site Error Notification
Please visit https://localhost:44356/admin/log for more information
Url opens whole log.
Improvement opens concrete log item
Subject: Site Error Notification
Please visit https://localhost:44356/admin/log?id=30231 for more information

Log notification improvement

---

Oqtane.Server/Controllers/FileController.cs
Oqtane.Server/Controllers/SqlController.cs
Oqtane.Server/Extensions/OqtaneSiteAuthenticationBuilderExtensions.cs

I found some cases when exception is throw but not recorded in log.

Exception is not saved to log

---

Oqtane.Server/Controllers/ModuleController.cs

Added the Deleted data to Module from the PageModule

Fix for Recycle bin not showing Deleted Date (Issue #2234)

---

Oqtane.Client/Resources/Themes/OqtaneTheme/ThemeSettings.resx

Missing Resource string added ResourceKey="Scope"

Added Missing Resource from Oqtane Theme Settings

---

Oqtane.Server/Startup.cs

Allows to have different configs in different enviroments.

Fixed loading of alternative appsettings "appsettings.{env.EnvironmentName}.json"

---

Oqtane.Client/Services/FileService.cs

FileService fix

---

Oqtane.Client/Installer/Installer.razor
Oqtane.Client/Themes/BlazorTheme/Themes/Default.razor
Oqtane.Client/Themes/OqtaneTheme/Themes/Default.razor
Oqtane.Server/wwwroot/Themes/Templates/External/Client/Themes/Theme1.razor

Replaced Bootstrap cloudflare versions and Integrity keys to match 5.2.0

Updated Bootstrap to 5.2

---

Oqtane.Client/Modules/Admin/RecycleBin/Index.razor
Oqtane.Client/Modules/Admin/UserProfile/Index.razor

When deleting large blocks of Pages, Modules or Notifications there was currently no visual feedback so added the ModuleInstance.ShowProgressIndicator() and ModuleInstance.HideProgressIndicator() calls to these processes.

Added Progress Indicator 

---

Oqtane.Server/Pages/_Host.cshtml.cs

Truncate UserAgent for save to Visitors table #2337

---

Oqtane.Server/Migrations/EntityBuilders/BaseEntityBuilder.cs

Some methods failing in BaseEntityBuilder if Schema is not null.

Some methods failing in BaseEntityBuilder if Schema is not null.

---

Oqtane.Server/Controllers/FileController.cs

Backslash fix.

---

Oqtane.Client/Modules/Controls/Pager.razor
Oqtane.Server/wwwroot/css/app.css

Currently the mouse pointer shows the Selector icon when hoovered over the page number buttons. This is an update changing the icon to the Pointer icon.
Updated the CSS class name to 'app-pager-pointer' in app.css and the Component.

A change to the Pager bar to set the mouse pointer to pointer

---

Oqtane.Client/Modules/Admin/RecycleBin/Index.razor

Now when deleting Pages or Modules the current page is shown and not reset to the first page.

Add OnPageChangePage to the Page and the Module Pagers in Recycle Bin

---

Oqtane.Client/Modules/Admin/UserProfile/Index.razor

If there are no Notifications then the button is not displayed.

Hide the ActionDialog Button for  "Clear Notifications" 

---

Oqtane.Client/Modules/Admin/RecycleBin/Index.razor

Modules and all related records now correctly deleted from the database.

Fix Clearing modules from the Recycle Bin

---

Oqtane.Client/Installer/Installer.razor
Oqtane.Client/Modules/Admin/Login/Index.razor
Oqtane.Client/Modules/Admin/Register/Index.razor
Oqtane.Client/Modules/Admin/Reset/Index.razor
Oqtane.Client/Modules/Admin/Site/Index.razor
Oqtane.Client/Modules/Admin/UserProfile/Index.razor
Oqtane.Client/Modules/Admin/Users/Add.razor
Oqtane.Client/Modules/Admin/Users/Edit.razor

Added  tabindex="-1" to the Button control so that focus is not received and passed the the following control.

Fix for #2728 Toggle Password button focus

---

Oqtane.Server/Pages/Sitemap.cshtml.cs

Added the Module Settings to the Module parameter passed in the GetUrls interface call,

Fix for #2718 SiteMap functionality missing Settings 

---

azuredeploy.json

1. removed depends on connection strings
2. Moved sku outside properties for type Microsoft.Web/serverfarms and added various app plans
3. Removed worker size and replaced with instance capacity
4. Replaced database and sqlserver to use various editions
5. Updated ApiVersions for various types

Invalid template when I try and use the Deploy to Azure button

---

Oqtane.Client/Services/FileService.cs

Normalize path and add '/' to end when needed

FileService backslash fix

---

Oqtane.Server/wwwroot/Modules/Templates/External/Client/Modules/[Owner].[Module]/ModuleInfo.cs

Fix for #2870
Description Tag changed from [Module] to [Description]

Fix for External Module Description not updated

---

Oqtane.Client/Modules/Admin/Users/Roles.razor

Closes #2955 User Roles Effective and Expiry date Rendering as Text

Closes #2955 User Roles Effective and Expiry date Rendering as Text

---

Oqtane.Client/Themes/Controls/Container/ModuleActions.razor

Updated the <ul> tag with a role attribute of button, now all items and sub items display the correct mouse pointer.

ModuleActions not displaying the correct mouse pointer

---

Oqtane.Client/Oqtane.Client.csproj
Oqtane.Server/wwwroot/Modules/Templates/External/Client/[Owner].Module.[Module].Client.csproj
Oqtane.Server/wwwroot/Themes/Templates/External/Client/[Owner].Theme.[Theme].Client.csproj

Removed RazorLangVersion tag from Client project files

---

Oqtane.Client/Modules/Admin/UserProfile/Index.razor
Oqtane.Client/Modules/Admin/UserProfile/View.razor
Oqtane.Client/Services/Interfaces/INotificationService.cs
Oqtane.Client/Services/NotificationService.cs
Oqtane.Server/Controllers/NotificationController.cs
Oqtane.Server/Migrations/Tenant/04000101_AddNotificationIsRead.cs
Oqtane.Server/Repository/Interfaces/INotificationRepository.cs
Oqtane.Server/Repository/NotificationRepository.cs
Oqtane.Shared/Models/Notification.cs

To address issue #2974 added IsRead Property to Notifications.
Notifications will be in Bold until they are Viewed upon which they are marked IsRead = true and not bold upon second view.

[ENHANCE] - Added IsRead property to Notifications

---

Oqtane.Server/wwwroot/Themes/Templates/External/[Owner].Theme.[Theme].sln

Remove Build for Oqtane Server in ConfigManger

Remove Build for Oqtane Server in ConfigManger

---

Oqtane.Server/Migrations/Tenant/04000101_AddNotificationIsRead.cs

The Down Path drops column IsPublic this is the wrong column the correct column is IsRead.

The Down path is incorrect 

---

Oqtane.Client/Modules/Admin/Users/Index.razor
Oqtane.Server/wwwroot/css/app.css

Added Sorting to User management component.

User management sort

---

Oqtane.Client/Themes/Controls/Theme/ControlPanel.razor

Added top margin to the Module Management section

Fixed up margins in Control Panel

---

Oqtane.Server/wwwroot/Modules/Templates/External/Client/Services/[Module]Service.cs

This fix is to handle a returned null from the database.  This issue came to light while using Postgresql

Fixes Module Creator problem  #3041

---

Oqtane.Client/Modules/Admin/Files/Edit.razor

This is due to the public virtual string Title can not use the Localize instance as it not yet created so error with null reference.

Trans keys

---

Oqtane.Client/Modules/Admin/ModuleDefinitions/Add.razor
Oqtane.Client/Modules/Admin/ModuleDefinitions/Edit.razor
Oqtane.Client/Modules/Admin/Site/Index.razor
Oqtane.Client/Modules/Admin/Themes/Add.razor
Oqtane.Client/Properties/launchSettings.json
Oqtane.Client/Resources/Modules/Admin/ModuleDefinitions/Add.resx
Oqtane.Client/Resources/Modules/Admin/Site/Index.resx
Oqtane.Client/Resources/Modules/Admin/Themes/Add.resx
Oqtane.Client/Resources/Modules/Controls/PermissionGrid.resx

Fix missing translations part 2

---

Oqtane.Client/Modules/Admin/Users/Index.razor

This emphasizes that the header is clickable.

Update the TH with link-primary Decoration classes

---

Oqtane.Client/Themes/Controls/Theme/ControlPanel.razor

This fix is related to issue #3163

[FIX] Added the ability to clear the Message in control panel

---

Oqtane.Client/Modules/Admin/UserProfile/View.razor

The replay textarea can now be used to enter a reply to the notification.

Removed the ReadOnly attribute in the Notifications Reply TextArea

---

Oqtane.Client/Modules/Admin/Reset/Index.razor

This adds the same functionality that already exists in the UserProfile module.
@microsoft-github-policy-service agree

Add password complexity requirements message to password Reset module.

---

Oqtane.Client/Modules/Admin/Profiles/Index.razor

When adding additional profile fields, this enhancement makes it easier to see details of the profile fields for the purpose of field organization.

Update to Profiles field list to include Title, Category and ViewOrder

---

Oqtane.Server/wwwroot/css/app.css

This simply fixes a typo and I will include this in my next PR with styles for the search UI control.
In the event the other is not accepted this should be.

Fix typo in app.css

---

Oqtane.Client/Modules/Admin/Users/Index.razor
Oqtane.Client/Resources/Modules/Admin/Site/Index.resx
Oqtane.Client/Resources/Modules/Admin/Users/Index.resx

Fix for  Site 'SMTP retention' is not in resource file (Issue #3301) Resx update with .Text and .HelpText
Fix for Users 'Import Users' is not in resource file #3304

Fix for  Site 'SMTP retention' is not in resource file (Issue #3301) and #3304 Users 'Import Users' resource

---

Oqtane.Client/Modules/Controls/Pager.razor
Oqtane.Client/Resources/Modules/Controls/Pager.resx

Localized the new Search Buttons
Added a Localized Placeholder that will display what columns are being searched.

Pager Search Localization

---

Oqtane.Client/Themes/Controls/Theme/ControlPanel.razor
Oqtane.Client/Themes/Controls/Theme/LanguageSwitcher.razor

Fixes the issue in the Language selector.

Fix for #3374 Backward compatability

---

Oqtane.Server/appsettings.json

OK this PR is targeting the correct branch as a test so I can make pull requests properly if I have any future contributions.
On to testing.

Remove default connection data

---

Oqtane.Client/App.razor

cool, branch still targeted properly, not to get some work done!

Removes unnecessary added space from upgrade to .NET 8

---

Oqtane.Client/Modules/Admin/UserProfile/Add.razor
Oqtane.Client/Modules/Admin/UserProfile/Index.razor
Oqtane.Client/Modules/Admin/UserProfile/View.razor
Oqtane.Client/Resources/Modules/Admin/UserProfile/Add.resx
Oqtane.Client/Resources/Modules/Admin/UserProfile/View.resx
Oqtane.Server/Controllers/NotificationController.cs

- fixed missing localization in View.razor (includes labels and all other static text)
- fixed UI navigation back to Index.razor to include tab=Navigation querystring parameter
- fixed IsRead property update in View.razor to only occur for messages received
- fixed UpdateNotificationAsync API to update based on FromUserId or ToUserId
- included username AutoComplete in Add.razor

fixes to notifications UI in user profile

---

Oqtane.Server/Extensions/OqtaneSiteAuthenticationBuilderExtensions.cs

Auth cookie expiration time ist set to value provided in Setting "LoginOptions:CookieExpiration" (if provided).

Added auth cookie expiration for external login via OAuth2.

---

Oqtane.Client/Themes/Controls/Theme/LoginBase.cs

Updated the LoginBase, if the URI doesn't contain the login URL then the NavigationManager is updated.

Fix #3539 for Multiple click on login button

---

Oqtane.Client/Modules/Admin/ModuleDefinitions/Edit.razor
Oqtane.Client/Resources/Modules/Admin/ModuleDefinitions/Edit.resx

This enhancement enables a check on where the moduleis used before it is deleted

Module Management Ehancement - show where modules are used.

---

Oqtane.Client/Modules/Admin/ModuleDefinitions/Edit.razor

Accidentally pushed this to Leighs repo.
This PR simply corrects a formatting issue.

Correct formatting of _pagesWithModules declaration

---

Oqtane.Client/Modules/Admin/Modules/Settings.razor
Oqtane.Client/Modules/Admin/Pages/Add.razor
Oqtane.Client/Modules/Admin/Pages/Edit.razor
Oqtane.Client/Modules/Admin/Users/Roles.razor
Oqtane.Client/Resources/Modules/Admin/Modules/Settings.resx
Oqtane.Client/Resources/Modules/Admin/Pages/Add.resx
Oqtane.Client/Resources/Modules/Admin/Pages/Edit.resx
Oqtane.Client/Resources/SharedResources.resx
Oqtane.Client/Themes/Controls/Theme/LoginBase.cs
Oqtane.Client/UI/SiteRouter.razor
Oqtane.Server/Controllers/ModuleController.cs
Oqtane.Server/Controllers/SiteController.cs
Oqtane.Server/Migrations/Tenant/05010001_AddPageEffectiveExpiryDate.cs
Oqtane.Server/Migrations/Tenant/05010002_AddPageModuleEffectiveExpiryDate.cs
Oqtane.Shared/Models/Module.cs
Oqtane.Shared/Models/Page.cs
Oqtane.Shared/Models/PageModule.cs
Oqtane.Shared/Shared/Utilities.cs

This is complete excluding Reporting and Notifications which can be added at a later date.  I just really wanted to get the schema and the functionality into place.

Start Date and Expiry Date for Module instances and Pages #3538

---

Oqtane.Client/Services/Interfaces/IModuleService.cs
Oqtane.Client/Services/Interfaces/INotificationService.cs
Oqtane.Client/Services/Interfaces/IPageModuleService.cs
Oqtane.Client/Services/Interfaces/IProfileService.cs
Oqtane.Client/Services/Interfaces/ISiteService.cs
Oqtane.Client/Services/Interfaces/ISiteTemplateService.cs
Oqtane.Client/Services/Interfaces/IThemeService.cs
Oqtane.Shared/Documentation/readme.md

Fixes #3623
Resolves Currently Known Oqtane Documentation spelling errors.

Documentation spelling correction.  Fixes #3623

---

Oqtane.Client/Modules/Admin/Jobs/Edit.razor
Oqtane.Client/Resources/Modules/Admin/Jobs/Edit.resx

Checks that the Start date starts before the End date. Message added to Resx.
Corrected a small UI formatting issue.

Start end End date Range check on Job Items

---

Oqtane.Server/wwwroot/Themes/Oqtane.Themes.OqtaneTheme/Theme.css
Oqtane.Server/wwwroot/Themes/Templates/External/Client/wwwroot/Themes/[Owner].Theme.[Theme]/Theme.css

Added white-space: nowrap; to the .app-menu .nav-item

Menu theme fix #3680

---

Oqtane.Maui/wwwroot/css/app.css

Fixes: #3795
Synchronizes recent server project app.css style:
```
.app-form-button {
display: inline-block;
}
```

adds app-form-button styles to sync with Oqtane.Server App.css - Fixes #3795

---

Oqtane.Client/Modules/Admin/Pages/Edit.razor

Fixes #3828
This pull request simply adds reload "true" boolean to the SavePage, NavigateTo() method in order to ensure displaying updated settings like when adding the icon to a page after it does not have one initially.
This will ensure a reload of the page so content is refreshed with latest page settings updates saved.
This code:
After adding a page and editing it to add an icon results in:
On Save.
This code:
Add a page again with new code then edit the page to add the new icon:
Results 
This clearly shows how this pull request updates the UI with reloading the browser on save.
There are other ways that may achieve the same results with possibly introducing a refresh instead of reload.  However this is how we have accomplished similar issues in the admin control panel in the past. …

Admin\Pages\Edit.razor: Adds reload "true" boolean to the SavePage, NavigateTo() method - Fixes #3828

---

Oqtane.Server/Oqtane.Server.csproj

This pull request updates the Microsoft.Data.SqlClient package reference in the Oqtane.Server project file to version 5.2.0.

Updates Oqtane.Sever.csproj Microsoft.Data.SqlClient package reference version to 5.2.0

---

Oqtane.Client/Themes/AdminContainer.razor

Reverts oqtane/oqtane.framework#3938

Revert "Fix #3927: change to async method to avoid the exception."

---

Oqtane.Server/wwwroot/Modules/Templates/External/Client/[Owner].Module.[Module].Client.csproj
Oqtane.Server/wwwroot/Modules/Templates/External/Server/[Owner].Module.[Module].Server.csproj

Fixes #4033
Updates packages for module creator template to match framework dependencies to version 8.0.3.

Fixes #4033: Updates Module creator template package references to 8.0.3

---

Oqtane.Client/Modules/Admin/Modules/Settings.razor
Oqtane.Client/Modules/Admin/Pages/Add.razor
Oqtane.Client/Modules/Admin/Pages/Edit.razor

Fix #4066: set the RenderModeBoundary instance.

Fix #4066: set the RenderModeBoundary instance.

---

Oqtane.Client/Modules/Controls/ActionLink.razor

Fix #4074: use the correct property value.

Fix #4074: use the correct property value.

---

Oqtane.Server/wwwroot/Modules/Templates/External/Package/[Owner].Module.[Module].Package.csproj
Oqtane.Server/wwwroot/Themes/Templates/External/Package/[Owner].Theme.[Theme].Package.csproj

fix #4103 - Visual Studio build acceleration breaks Oqtane Module build process

---

Oqtane.Server/Controllers/ModuleDefinitionController.cs

InitializeTokenReplace not setting the correct PackageReference

---

Oqtane.Client/Modules/Admin/Themes/Index.razor

Deleted a rouge TD in the themes index table

Rogue TD in table

---

Oqtane.Client/Modules/Controls/RichTextEditor.razor
Oqtane.Client/Modules/Controls/RichTextEditorInterop.cs
Oqtane.Server/wwwroot/js/quill-interop.js

Fix #4158: insert image into correct position.

Fix #4158: insert image into correct position.

---

Oqtane.Client/Modules/Admin/Logs/Index.razor
Oqtane.Client/Modules/Admin/ModuleDefinitions/Index.razor
Oqtane.Client/Modules/Admin/Pages/Index.razor
Oqtane.Client/Modules/Admin/Profiles/Index.razor
Oqtane.Client/Modules/Admin/Users/Index.razor
Oqtane.Client/Modules/Admin/Visitors/Index.razor
Oqtane.Client/Resources/Modules/Admin/Modules/Settings.resx
Oqtane.Client/Resources/Modules/Admin/Profiles/Index.resx

Resx entry for Module Settings Permissions tab

Fix for #4168 #4170 missing Translations

---

Oqtane.Client/Resources/Modules/Admin/Modules/Settings.resx

ModuleSettings ContainerSettings #4211

ModuleSettings ContainerSettings #4211

---

Oqtane.Server/Components/App.razor

Fix #4254: remove the redundant space.

Fix #4254: remove the redundant space.

---

Oqtane.Client/Themes/BlazorTheme/Themes/Default.razor
Oqtane.Client/Themes/Controls/Theme/Search.razor
Oqtane.Client/Themes/OqtaneTheme/Themes/Default.razor
Oqtane.Server/wwwroot/Themes/Oqtane.Themes.BlazorTheme/Theme.css
Oqtane.Server/wwwroot/Themes/Oqtane.Themes.OqtaneTheme/Theme.css

Fix #4309: make searchbox responsive.

Fix #4309: make searchbox responsive.

---

Oqtane.Client/Modules/Admin/Site/Index.razor
Oqtane.Server/Infrastructure/DatabaseManager.cs

Reverts oqtane/oqtane.framework#4417

Revert "disable prerendering by default for static rendered sites"

---

Oqtane.Server/Infrastructure/LogManager.cs

{alias.Protocol} return with "://"

Removed the extra "://" from the Log Manager

---

Oqtane.Client/Oqtane.Client.csproj
Oqtane.Database.PostgreSQL/Oqtane.Database.PostgreSQL.csproj
Oqtane.Database.SqlServer/Oqtane.Database.SqlServer.csproj
Oqtane.Database.Sqlite/Oqtane.Database.Sqlite.csproj
Oqtane.Maui/Oqtane.Maui.csproj
Oqtane.Server/Oqtane.Server.csproj
Oqtane.Server/wwwroot/Modules/Templates/External/Client/[Owner].Module.[Module].Client.csproj
Oqtane.Server/wwwroot/Modules/Templates/External/Server/[Owner].Module.[Module].Server.csproj
Oqtane.Server/wwwroot/Themes/Templates/External/Client/[Owner].Theme.[Theme].Client.csproj
Oqtane.Shared/Oqtane.Shared.csproj
Oqtane.Updater/Oqtane.Updater.csproj

This PR Updates project files version to 5.2.1 and dependencies to latest 8.0.8
Fixes #4514
It also updates the readme file to be updated with date TBA and updates to list.

Fixes #4514 - Update version 5.2.1 and dependencies

---

Oqtane.Database.MySQL/Oqtane.Database.MySQL.csproj

I believe this was not bumped up in last release since there were no dependencies updated.  I want to be sure this got fixed this release so just a minor update/fix.
Fix in addition to Fix #4583

Update MySQL Project File Version - Prepare for 5.2.2

---

Oqtane.Client/Modules/Admin/Site/Index.razor

FIX #4655 - autocomplete="off" for SMTP Username/Password

---

Oqtane.Server/Databases/Interfaces/IMultiDatabase.cs

fixes #4669 Remove unnecessary usings in IMultiDatabase.cs

Fixes #4669 - Remove unnecessary usings in IMultiDatabase.cs

---

Oqtane.Server/Repository/PageRepository.cs

The issue:
Step to Reproduce:
- I have a simple page with a simple Html module in it.
- First I soft-delete the page.
- Then I hard-delete the same page from Recycle Byn.
Spot the issue:
All seems to go well on UI but looking at the record in the db I see a stale record of that page still present (module and permission are correctly deleted, but not the record in the page db table).
Since the page on db has no permission linked to it I won't see that page anywhere in the UI. But it will remain in database forever.
This happens in SqlServer and SqlLite (an i guess in any other db, its an entity framework context thing).
The problem is the use of multiple opened ef context in deletion of module of the page (one ef dbcontext) and the page itself (another ef dbcontext): the fix in code is …

Hard deletion of page more robust use of entity framework contexts

---

Oqtane.Database.MySQL/Oqtane.Database.MySQL.csproj

Fixes #4735 - Updates MySQL.Data to 9.1.0

Fixes #4735 - Update MySQL.Data to 9.1.0

---

README.md

Fixes #4738 - Add Discord community button to README.md
- Added a button for joining the Oqtane Discord server
- Included a brief description encouraging community engagement

Fixes #4738 - Add Discord community button to README.md

---

Oqtane.Server/Oqtane.Server.csproj

Fixes #4776: Updates HtmlAgilityPack to 1.11.69

Fixes #4776: Updates HtmlAgilityPack to 1.11.69

---

Oqtane.Server/Oqtane.Server.csproj

Fixes #4792 - Updates Oqtane.Server.csproj Package Dependencies

Fixes #4792: Update Oqtane.Server.csproj Package Dependencies

---

Oqtane.Client/Modules/Admin/Modules/Settings.razor

This change will select the Settings tab only when the settings panel has an error.

Updated the Module Settings to use the new ActiveTab parameter

---

Oqtane.Client/Modules/Admin/Modules/Settings.razor
Oqtane.Client/Modules/Admin/Pages/Add.razor
Oqtane.Client/Modules/Admin/Pages/Edit.razor
Oqtane.Client/Modules/Controls/QuillJSTextEditor.razor
Oqtane.Client/Modules/Controls/TabPanel.razor
Oqtane.Client/Modules/Controls/TabStrip.razor

Reverts oqtane/oqtane.framework#4871

Revert "Rework for Tabstrip regression issue"

---

Oqtane.Client/Modules/Admin/Pages/Add.razor
Oqtane.Client/Modules/Admin/Pages/Edit.razor
Oqtane.Client/Modules/Controls/TabPanel.razor
Oqtane.Client/Modules/Controls/TabStrip.razor

Reverts oqtane/oqtane.framework#4828

Revert "Fix for Tabpanel is not updating the UI. #4778"

---

Oqtane.Client/Oqtane.Client.csproj
Oqtane.Database.MySQL/Oqtane.Database.MySQL.csproj
Oqtane.Database.PostgreSQL/Oqtane.Database.PostgreSQL.csproj
Oqtane.Database.SqlServer/Oqtane.Database.SqlServer.csproj
Oqtane.Database.Sqlite/Oqtane.Database.Sqlite.csproj
Oqtane.Maui/Oqtane.Maui.csproj
Oqtane.Package/Oqtane.Client.nuspec
Oqtane.Package/Oqtane.Framework.nuspec
Oqtane.Package/Oqtane.Server.nuspec
Oqtane.Package/Oqtane.Shared.nuspec
Oqtane.Package/Oqtane.Updater.nuspec
Oqtane.Package/install.ps1
Oqtane.Package/upgrade.ps1
Oqtane.Server/Oqtane.Server.csproj
Oqtane.Shared/Oqtane.Shared.csproj
Oqtane.Updater/Oqtane.Updater.csproj

Fixes #4961 
Updates Oqtane version to 6.0.2 and update related project dependencies to latest.

Fixes #4961 - Updates Oqtane version to 6.0.2 and update related project dependencies to latest.

---

Oqtane.Server/Oqtane.Server.csproj

Fixes Azure manual deployment build from local code build. May need an additional fix in MySQL library (Line 24 - MySQLDatabase.cs)

Update Oqtane.Server.csproj - MySQL deploy to Azure error

---

Oqtane.Client/Oqtane.Client.csproj
Oqtane.Database.MySQL/Oqtane.Database.MySQL.csproj
Oqtane.Database.PostgreSQL/Oqtane.Database.PostgreSQL.csproj
Oqtane.Database.SqlServer/Oqtane.Database.SqlServer.csproj
Oqtane.Database.Sqlite/Oqtane.Database.Sqlite.csproj
Oqtane.Maui/Oqtane.Maui.csproj
Oqtane.Server/Oqtane.Server.csproj
Oqtane.Server/wwwroot/Modules/Templates/External/Client/[Owner].Module.[Module].Client.csproj
Oqtane.Server/wwwroot/Modules/Templates/External/Server/[Owner].Module.[Module].Server.csproj
Oqtane.Server/wwwroot/Themes/Templates/External/Client/[Owner].Theme.[Theme].Client.csproj
Oqtane.Shared/Oqtane.Shared.csproj

Fixes #5020: Updates package dependencies 9.0.1 (Latest)

Fixes #5020: Updates package dependencies 9.0.1 (Latest)

---

Oqtane.Server/Controllers/ThemeController.cs

update `SharedReference` to use "Oqtane.Shared" for PackageReference code

Minor fix in ThemeController.cs

---

Oqtane.Server/Oqtane.Server.csproj

Update Swashbuckle  to version 8.0

Swashbuckle Update

---

Oqtane.Server/Oqtane.Server.csproj

Swashbuckle.AspNetCore update from 8.1.0 > 8.1.1

Swagger Updated to latest

---

Oqtane.Server/Oqtane.Server.csproj
Oqtane.Server/wwwroot/Modules/Templates/External/Server/AssemblyInfo.cs

I will modify the server-side resource path as follows.
before:
[Owner].Module.[Module].Server.Oqtane
after:
[Owner].Module.[Module].Server

Modify the module's server-side resource path.

---

Oqtane.Client/Modules/ModuleBase.cs

Replaced the ReplaceTokens logic to replace all tokens in the string

Fix for ModuleBase ReplaceTokens #5332

---

Oqtane.Server/Oqtane.Server.csproj

update SixLabors.ImageSharp
update Swashbuckle.AspNetCore

Server References Updated

---

Oqtane.Maui/Oqtane.Maui.csproj

Fixes #5390
Updates Oqtane.Maui Solution Package Dependencies to 9.0.90

Fixes #5390: Updates Oqtane.Maui Solution Package Dependencies to 9.0.90

---

Oqtane.Server/wwwroot/Themes/Templates/External/Client/ThemeInfo.cs
Oqtane.Shared/Shared/Constants.cs

Updated and styles tested - reload.js needs still testing?

Discussion #5426 updated and returned to https://cdnjs.com/

---

Oqtane.Client/Oqtane.Client.csproj
Oqtane.Database.PostgreSQL/Oqtane.Database.PostgreSQL.csproj
Oqtane.Database.SqlServer/Oqtane.Database.SqlServer.csproj
Oqtane.Database.Sqlite/Oqtane.Database.Sqlite.csproj
Oqtane.Maui/Oqtane.Maui.csproj
Oqtane.Server/Oqtane.Server.csproj
Oqtane.Server/wwwroot/Modules/Templates/External/Client/[Owner].Module.[Module].Client.csproj
Oqtane.Server/wwwroot/Modules/Templates/External/Server/[Owner].Module.[Module].Server.csproj
Oqtane.Server/wwwroot/Themes/Templates/External/Client/[Owner].Theme.[Theme].Client.csproj
Oqtane.Shared/Oqtane.Shared.csproj

Oqtane Framework
Project Templates Module and Theme
MAUI solution
> [!IMPORTANT]  
> **SQLitePCLRaw.bundle_e_sqlite3 was not updated.** as this is a bundle and not the runtimes.

Updated Project Refs 9.0.8

---

Oqtane.Server/Oqtane.Server.csproj

Updated Microsoft.Data.SqlClient to 6.1.1

Microsoft.Data.SqlClient updated

---

Oqtane.Maui/Oqtane.Maui.csproj

Fixes #5501
Updates Maui Project Dependencies to version 9.0.100

Fixes #5501: Updates Maui Project Dependencies to version 9.0.100

---

Oqtane.Client/Modules/Admin/Jobs/Index.razor
Oqtane.Client/Resources/Modules/Admin/Jobs/Index.resx
Oqtane.Server/Infrastructure/Jobs/HostedServiceBase.cs

fix job status issue for disabled jobs

---

Oqtane.Client/Oqtane.Client.csproj
Oqtane.Package/Oqtane.Client.nuspec
Oqtane.Package/Oqtane.Server.nuspec
Oqtane.Server/Oqtane.Server.csproj

Updated Client Radzen.Blazo to 7.3.5
Updated Server HtmlAgilityPack 1.12.3

Package Updates

---

Oqtane.Client/Resources/Modules/Admin/Themes/Edit.resx

Update to Themes Editresx
