- Oqtane.Client/Shared/SiteRouter.razor
added nulcheck on page. 
when url is changed to nonexistent page exception was raised
> Missing nullcheck -> crash when 404

- Oqtane.Client/Modules/Controls/ActionDialog.razor
Adds an icon for the ActionDialog.
New Usage: 
```
<ActionDialog Header="Delete Page" IconName="trash" Message="@("Are You Sure You Wish To Delete The " + context.Name + " Page?")" Action="Delete" Security="SecurityAccessLevel.Admin" Class="btn btn-danger" OnClick="@(async () => await DeletePage(context))" />
```
> Adds an icon for the link/button.

- Oqtane.Shared/Oqtane.Shared.csproj
- Oqtane.Shared/Shared/Utilities.cs
- Oqtane.Test/Oqtane.Shared.Tests/UtilitiesTests.cs
FYI I found a little tiny bug with the old implementation when we have url like `https://contoso?pageId=4` it should be `https://contoso/?pageId=4` to meet the standard
> Simplify NavigateUrl using UriBuilder

- Oqtane.Server/Repository/SiteRepository.cs
When you add a new site template in the appconfig, the value is null. When adding the section and the value, the installation picks up your new template.
> Fix null value for site template.

- Oqtane.Server/Repository/SiteRepository.cs
The fix for #368 prevents the default site template from being used. The site builds, but the default three pages do not show.
> Fix empty string for default site template.

- Oqtane.Server/Startup.cs
Services GET returns null instead of exception :)
based on excellent blog, thanks to Havaii
https://weblog.west-wind.com/posts/2020/Feb/24/Null-API-Responses-and-HTTP-204-Results-in-ASPNET-Core
> Return JSON null instead of 204 status from controller

- Oqtane.Client/Services/NotificationService.cs
Removed space causing _siteid_ to always send a null value to the Notifications service.
For example, when navigating to the /profile page, the following is sent:
http://localhost:44357/~/api/Notification?%20siteid=1&direction=to&userid=1
The correct format should be the following:
http://localhost:44357/~/api/Notification?siteid=1&direction=to&userid=1
> Fix Notifications parameters

- Oqtane.Client/Modules/Admin/Profiles/Edit.razor
Adding a new profile property was going through the UpdateProfile method instead of AddProfile 
method. Now uses the AddProfile method when there was no pre-existing id as already used earlier in the same function for same destinction
> Fixed add profile property

- Oqtane.Client/Modules/Admin/ModuleCreator/Templates/External/Client/[Owner].[Module]s.Module.Client.csproj
Works without them.
error:
Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(195, 5): Duplicate base paths '/' for content root paths .......
https://gitter.im/aspnet/Blazor?at=5e915f6ee24b4d6c44fe1827
> ModuleCreator: WebAssembly references causes build error in some scenarios. 

- Oqtane.Server/Repository/ModuleDefinitionRepository.cs
Abstract classes should be filtered, cannot be instantiated.
> Ignore abstract classes at loading

- Oqtane.Server/Controllers/FolderController.cs
- Oqtane.Shared/Shared/Constants.cs
Apply the file and path naming rules found at [Naming Files, Paths, and Namespaces](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file)
Mitigate path traversal.
> Add File and Path rules

- Oqtane.Client/Modules/Admin/Site/Index.razor
Fixes #537 
_Edited:_
**Select Theme, Select Layout** and **Select Container** options removed from the dropdown lists for selecting site default theme, layout and container.
'<Select Theme>'  *** REMOVED ***
Blazor
Oqtane
**Reason:**
1.  This option will brick Oqtane Dashboard
2.  Oqtane is default option, why include "Select Theme" when you have label and help icon, too redundant and makes something more for your eyes to view that is irrelevant in a way self explanatory.
> Site Settings: removes ONLY " <Select Container>"Theme and Layout drop down options

- Oqtane.Shared/Extensions/AssemblyExtensions.cs
During tests adding third party dlls to external modules we have found an issue within the loading process of the external module. This issue is responsible that under some specific circumstances the loading process of the external module crashes with an exception.
This PR resolves the possible issue by changing the filter logic of types a little bit. Now the logic tests the reflected properties before the Type.isAssignableFrom method is called. This prevents that Type.isAssignableFrom is called for invalid types (e.g. abstract types etc.).
> Fixed type filtering in assembly extensions

- Oqtane.Client/Modules/Admin/UserProfile/View.razor
fixes #539  (references PR #540 closed)
Part 2 of Part 1 #585
Resolves issues with the user profile notifications area.
- Issue:  Enabled/Disabled input depending on view or reply (To/From)  
This was my original fix... all others are fall out from working in this area which is why this has been broken into two
- Enhancement:  Reply message page break line above '___' then date + subject + original conversation or message similar to email.
- Enhancement:  Message reply has empty line for cursor
- Enhancement:  Original Message shows up in text box that allows scrolling and line breaks.
-  To/From Form Table could be two if statements with two tables instead of many if statements inside columns, works as is, just not sure if I should approach that differently.  I can rewrite if desired.  I …
> To/From Fields enabled/disabled, reply message fix

- Oqtane.Client/Modules/Admin/UserProfile/Add.razor
- Oqtane.Client/Modules/Admin/UserProfile/View.razor
- Oqtane.Server/Controllers/UserController.cs
- Oqtane.Server/Oqtane.Server.csproj
- Oqtane.Server/Repository/NotificationRepository.cs
- Oqtane.Server/Scripts/Notification.01.00.01.00.sql
- Oqtane.Server/Scripts/Tenant.01.00.01.01.sql
- Oqtane.Shared/Models/Notification.cs
This PR adds the ability to send a notification based on a future datetime. The logic uses a new field in the Notification table named SendOn. To keep the current functionality with no breaking changes, the SendOn date is defaulted to ```UtcNow``` in the framework. 
In the Notificaiton repository class, an additional WHERE cause is added to ```GetNotifications``` so the List/IEnumerable of Notifications only includes notifications with a SendOn date before now.
A developer would use this by creating their own Notification object and adding a send on date that meets their needs.
> Send notification based on a future datetime

- Oqtane.Client/Modules/ModuleBase.cs
Currently the url parameter segments that are not variables are being discarded. It would be helpful to developers to be able to access the "action" segments, example:
`$"{{{parentId}}}/Edit/{{{childId}}}"` and `$"{{{parentId}}}/View/{{{childId}}}"`
Saving the "action" segments allows the developer to parse which "page" they are on if they want to ie: `Edit` or `View`
```csharp
if (UrlParamerters.ContainsKey("action1"))
{
switch (UrlParamerters["action1"])
{
case "Edit":
//set parameters
break;
case "View":
//set parameters
break;
default:
break;
}
}
> Url parameter helper enhancements

- Oqtane.Client/Modules/Admin/Pages/Add.razor
- Oqtane.Client/Modules/Admin/Pages/Edit.razor
Closes #626 
The reason for the Exception described in #626 was the fact that the path of a page contains to a unique index in the db. And because the "deleted" page still existed with the deleted flag also the path still existed. The creation of a page with the exact same name leads to an exact same path like the one that still exists. This fact than hearts the unique index rule during the db update.
This could also happen if an user with permissions to change or add pages enters a path for the page that already exists for the selected parent page.
With this PR a path validation was implemented that prevents a user to enter an already existing path.
> Page path validation

- Oqtane.Server/Infrastructure/InstallationManager.cs
When running Oqtane on Linux Theme installation is failing. The root cause appears to be the handling of the directory splitting in the **InstallationManager**. Here a fixed string is used.
This should be changed to `Path.DirectorySeparatorChar` to be handled based on the runtime platform.
I have tested this change on Ubuntu and Windows.
> Fix directory separator in InstallationManager

- Oqtane.Server/Controllers/FileController.cs
- Oqtane.Server/Controllers/FolderController.cs
- Oqtane.Server/Controllers/ModuleDefinitionController.cs
- Oqtane.Server/Controllers/UserController.cs
- Oqtane.Server/Infrastructure/DatabaseManager.cs
- Oqtane.Server/Infrastructure/SiteTemplates/DefaultSiteTemplate.cs
- Oqtane.Server/Repository/SiteRepository.cs
There are a few more places where path handling can be improved to be made platform agnostic.
I have changed several occurences where the last path element was a fixed string with a Windows directory separator.
> Fix directory separator for path operations

- Oqtane.Server/Oqtane.Server.csproj
It seems when you navigate to the Oqtane.Server folder and run ```dotnet publish``` there is an error. Adding a project reference to the Upgrade project fixes that error.
You can follow the discussion here at:
https://github.com/oqtane/oqtane.framework/discussions/681
> Add project reference for dotnet publish to work without errors.

- Oqtane.Client/Modules/Admin/ModuleCreator/Index.razor
Module pluralization was deleted in #683.
> Delete module pluralization in the location display.

- Oqtane.Client/UI/Pane.razor
Currently the Modules look a little squished like [This](https://i.imgur.com/TRJROTQ.png) because of  [This](https://i.imgur.com/JyXc1e4.png). This PR solves this by adding [This](https://i.imgur.com/MoEDxEM.png) so that it looks like [This](https://i.imgur.com/iHMuwa2.png)
> add default class 'container' for div in pane to avoid content squishing

- Oqtane.Client/UI/SiteRouter.razor
added after this discussion post was made: #765
This if statement just checks if the route is inside a Module, we do not need to check that anymore because the Index Page should always be displayed if we are not in the Module. ` if (module.ModuleId == moduleid && action != "")`  Which is why we set this `var action = Constants.DefaultAction;` Which basically the same thing that this was doing: `else{module.ModuleType = typename.Replace(Constants.ActionToken, Constants.DefaultAction);}`
I did test this with an External Module and the internal HtmlText Module, I did not find any errors.
> Allows page to find Custom Index page in Module from Actions Property

- Oqtane.Server/Controllers/InstallationController.cs
- Oqtane.Server/Extensions/OqtaneServiceCollectionExtensions.cs
Make sure that the application will not crash if satellite assemblies folders are missing, this could happen due any reason for example:
- Satellite assemblies for a particular culture are not deployed correctly
- The `SupportedCultures` contains non deployed resources, this could be done by adding extra cultures accidentally
> Skip missed satellite assemblies forlders

- Oqtane.Client/Services/ServiceBase.cs
Simple improvement to keep the code DRY.
> Refactor to eliminate repetitive code.

- Oqtane.Server/Extensions/WebHostBuilderExtensions.cs
- Oqtane.Server/Program.cs
- Oqtane.Server/Startup.cs
This PR will:
- Simplify the localization configuration settings
- More important it uses `ILocalizationManager`, so no need for code redundancy to make initialize the default culture and supported cultures
> Simplify localization settings configurations

- Oqtane.Client/Modules/Controls/Label.razor
- Oqtane.Client/Oqtane.Client.csproj
- Oqtane.Client/Program.cs
> Support label localization

- Oqtane.Client/Modules/Controls/Label.razor
- Oqtane.Client/Oqtane.Client.csproj
- Oqtane.Client/Program.cs
- Oqtane.Server/Startup.cs
> Use ServiceActivator instead of IHttpContextAccessor

- Oqtane.Client/Modules/Controls/Label.razor
- Oqtane.Client/Modules/Controls/LocalizableComponent.cs
@sbwalker this tested and will make component localization more easier
> Localizable component

- Oqtane.Server/Startup.cs
- Oqtane.Shared/Shared/PolicyNames.cs
Factor out Policy Names
Change AppDomain to AppContext (AppDomain just passes it through to AppContext and AppDomain is basically considered legacy).
> Factor out Policy Names

- Oqtane.Server/AssemblyInfo.cs
- Oqtane.Server/Infrastructure/LogManager.cs
> Localize log messages

- Oqtane.Client/Modules/Controls/ActionDialog.razor
I'm working on Arabic translation for Oqtane, I just found that I miss to localize `Text` for `ActionDialog`
> Localize ActionDialog.Text

- Oqtane.Client/Themes/Controls/LoginBase.cs
- Oqtane.Client/UI/SiteRouter.razor
Url was transformed to 
https://xxxx.yyy/login/!/returnurl=test/Detail
instead of
https://xxxx.yyy/login?returnurl=test/Detail
> Fix - return to url during login fail when returnurl contains "/"

- .gitignore
During development I notice that whenever you upload a file, the git traking the `Content` folder, so it will be nice to ignore this folder
> Add Content folder to .gitignore

- Oqtane.Client/Modules/Admin/Files/Add.razor
- Oqtane.Client/Modules/Admin/Files/Edit.razor
- Oqtane.Client/Modules/Admin/Files/Index.razor
- Oqtane.Client/Modules/Admin/Jobs/Index.razor
- Oqtane.Client/Modules/Admin/Jobs/Log.razor
- Oqtane.Client/Modules/Admin/Logs/Index.razor
- Oqtane.Client/Modules/Admin/RecycleBin/Index.razor
- Oqtane.Client/Modules/Admin/Roles/Index.razor
- Oqtane.Client/Modules/Admin/Roles/Users.razor
- Oqtane.Client/Modules/Admin/Sites/Index.razor
- Oqtane.Client/Modules/Admin/Sql/Index.razor
- Oqtane.Client/Modules/Admin/Tenants/Index.razor
- Oqtane.Client/Modules/Admin/Themes/Index.razor
- Oqtane.Client/Modules/Admin/UserProfile/Index.razor
- Oqtane.Client/Modules/Admin/UserProfile/View.razor
- Oqtane.Client/Modules/Admin/Users/Add.razor
- Oqtane.Client/Modules/Admin/Users/Index.razor
- Oqtane.Client/Modules/Admin/Users/Roles.razor
- Oqtane.Client/Modules/Controls/AuditInfo.razor
- Oqtane.Client/Modules/Controls/FileManager.razor
- Oqtane.Client/Modules/Controls/PermissionGrid.razor
- Oqtane.Client/Modules/Controls/TriStateCheckBox.razor
- Oqtane.Client/Themes/Controls/ControlPanel.razor
I'm working to localize Oqtane in Arabic, this PR should fix all the missing localizations strings
> Add missing localization strings

- Oqtane.Server/Controllers/FileController.cs
- Oqtane.Server/Extensions/StringExtensions.cs
- using PhysicalFile framework method for serving file (current implementation causes file locks and 500 error at heavy load)
- Add correct mimetype to header based on file extension
> FileController fix

- Oqtane.Client/Themes/Controls/ControlPanel.razor
- Oqtane.Client/Themes/Controls/LanguageSwitcher.razor
> Show LanguageSwitcher if more than one culture

- Oqtane.Server/wwwroot/Modules/Templates/External/Client/AssemblyInfo.cs
1. No chnages required for the internal module, because we already have a proper `RootNamespace`
2. `RootNamespace` added for the external module to make it localize ready, but still there are two steps to make the localization works. I think we need to write some docs about this
/cc @sbwalker  @nicpitsch
> Make external module localize ready

- Oqtane.Client/Modules/Admin/Roles/Users.razor
> Order users by display name

- Oqtane.Client/Modules/Admin/Modules/Settings.razor
- Oqtane.Shared/Interfaces/ISettingsControl.cs
Settings of module is not saved because UpdateSettings method cannot be invoked
> Settings Fix

- Oqtane.Server/Repository/LanguageRepository.cs
@sbwalker this avoid to reset all the languages - even for other sites - when a newly added language is set to the default
> Reset IsDefault per site Id for newly added language

- Oqtane.Client/Themes/Controls/FontIcon.razor
- Oqtane.Client/Themes/Controls/FontIcon.razor.cs
- Oqtane.Client/Themes/Controls/MenuHorizontal.razor
- Oqtane.Client/Themes/Controls/MenuItemsBase.cs
- Oqtane.Client/Themes/Controls/MenuItemsHorizontal.razor
- Oqtane.Client/Themes/Controls/MenuItemsHorizontal.razor.cs
- Oqtane.Client/Themes/Controls/MenuItemsVertical.razor
- Oqtane.Client/Themes/Controls/MenuItemsVertical.razor.cs
- Oqtane.Client/Themes/Controls/MenuVertical.razor
@sbwalker I have modified the horizontal menu logic to include two levels of menu items. It now renders the item correctly. I'll start on the vertical now and PR it next.
> Fixes to horizontal menu logic. Now supports two levels of menu items.

- Oqtane.Server/Pages/_Host.cshtml.cs
Addresses https://github.com/oqtane/oqtane.framework/discussions/1094
> Fix the localization manager resolution

- Oqtane.Client/Modules/Admin/ModuleCreator/Index.razor
- Oqtane.Client/Services/FileService.cs
- Oqtane.Client/Services/FolderService.cs
- Oqtane.Server/Extensions/OqtaneServiceCollectionExtensions.cs
Tested on Apple mac and Windows
> DirectorySeparator issue when black or forward slash.

- Oqtane.Client/Modules/Controls/Section.razor
From Bootstrap
_Usage
The collapse plugin utilizes a few classes to handle the heavy lifting:
.collapse hides the content
**.collapse .show** shows the content
.collapsing is added when the transition starts, and removed when it finishes_
> #1106 Fix issue where Section would not initialize Expanded.

- Oqtane.Client/Modules/Admin/Files/Index.razor
Added a format to the context.size 
`string.Format("{0:0.00}", ((decimal)context.Size / 1000)) KB`
> Fix for #1134 Files size incorrect when less than 1000 bytes

- README.md
This Pull Request accomplishes two minor goals.  By adding the ".idea" folder to the gitignore file, developers can use Jetbrains Rider as their development tool without having to manually reject Rider's configuration options.  The .idea folder is like the Viusal Studio .vs folder. Secondly, by adding the gitignore file and the README file to the Solution Files folder, these files become easily editable in Visual Studio or Rider.
> Add gitignore and README to Solution files and ad support for Jetbrains Rider

- Oqtane.Server/Extensions/DbContextOptionsBuilderExtensions.cs
- Oqtane.Server/Infrastructure/DatabaseManager.cs
- Oqtane.Server/Repository/Context/DBContextBase.cs
- Oqtane.Server/Repository/Context/DbContextUtils.cs
- Oqtane.Server/Repository/Context/InstallationContext.cs
- Oqtane.Server/Repository/Context/MasterDBContext.cs
This is a preparative refactoring for the Multi-Database feature to locate all database configuration in one file.  I have created a new extension method for the DbContextOptionsBuilder class, with a single method UseOqtaneDatabase, which currently just calls the extension method UseSqlServer. 
In all locations where UseSqlServer is called I have replaced the call with UseOqtaneDatabase.  This locates all database configuration in a single place in preparation for the multi-database support.
The current impact is zero.
> Create new UseOqtaneDatabase extension method

- Oqtane.Client/Modules/Admin/Logs/Index.razor
> Rows -> Maximum Records

- Oqtane.Client/UI/Pane.razor
After finish Edit, there's a class "container" which is conflict with Bootstrap that cause an issue on Full-width pane.
> Remove admin border after edit

- Oqtane.Server/Repository/AliasRepository.cs
When alias is not found in alias table, Oqtane fails with exception in SiteRouter.razor line 108 - alias is null. This solution allows define default alias "*" for determine a site which will be shown when alias is not found. 
#1156
> Default Alias

- Oqtane.Client/Installer/Controls/LocalDBConfig.razor
- Oqtane.Client/Installer/Controls/MySQLConfig.razor
- Oqtane.Client/Installer/Controls/PostgreSQLConfig.razor
- Oqtane.Client/Installer/Controls/SqlServerConfig.razor
- Oqtane.Client/Installer/Controls/SqliteConfig.razor
- Oqtane.Client/Installer/Installer.razor
- Oqtane.Client/Modules/Admin/Sites/Add.razor
- Oqtane.Client/Program.cs
- Oqtane.Client/_Imports.razor
- Oqtane.Database.MySQL/MySQLDatabase.cs
- Oqtane.Database.PostgreSQL/PostgreSQLDatabase.cs
- Oqtane.Database.Sqlite/SqliteDatabase.cs
- Oqtane.Server/Databases/LocalDbDatabase.cs
- Oqtane.Server/Databases/SqlServerDatabase.cs
- Oqtane.Server/Databases/SqlServerDatabaseBase.cs
- Oqtane.Shared/Interfaces/IDatabaseConfigControl.cs
- Oqtane.Shared/Interfaces/IOqtaneDatabase.cs
- Oqtane.Shared/Models/Database.cs
- Oqtane.Shared/Shared/OqtaneDatabaseBase.cs
The initial code for handling multiple databases required the "Server" assemblies to be deployed to the Blazor client.  This change adds new Razor Components for each database that work in both the Installer and AddSite Components.
> Adding new DatabaseConfig components in the Client project for supported Databases

- Oqtane.Client/Modules/Admin/Languages/Add.razor
- Oqtane.Client/Modules/Admin/Languages/Index.razor
This includes:
- Show the Default language in the languages list
- Ability to delete the default language if it's a last language alongside with English, this is useful when the website is no longer support multilingual
- Fix the UX when adding a new language
> Few Enhancements in Language Management

- Oqtane.Client/Installer/Installer.razor
- Oqtane.Client/Modules/Admin/Sites/Add.razor
- Oqtane.Database.MySQL/MySQLDatabase.cs
- Oqtane.Database.PostgreSQL/PostgreSQLDatabase.cs
- Oqtane.Database.SqlServer/LocalDbDatabase.cs
- Oqtane.Database.SqlServer/SqlServerDatabase.cs
- Oqtane.Database.Sqlite/SqliteDatabase.cs
- Oqtane.Server/Controllers/DatabaseController.cs
- Oqtane.Server/Infrastructure/DatabaseManager.cs
- Oqtane.Server/Repository/Context/DBContextBase.cs
- Oqtane.Server/Repository/Context/MasterDBContext.cs
- Oqtane.Server/Repository/SqlRepository.cs
- Oqtane.Shared/Interfaces/IOqtaneDatabase.cs
- Oqtane.Shared/Models/Database.cs
- Oqtane.Shared/Shared/OqtaneDatabaseBase.cs
This PR fixes issue #1317 , by using the fully-qualified type name as the database type.
> Switch DBType to use the fully-qualified type name rather than a simple name

- Oqtane.Server/Migrations/02010002_ChangeFolderNameAndPathColumnsSize.cs
- Oqtane.Server/Migrations/EntityBuilders/BaseEntityBuilder.cs
- Oqtane.Server/Migrations/Framework/ForeignKey.cs
The new Migration introduced to extend the length of the Path property of the Folder object throws an exception when installing in MySQL.  MySQL complains if you are dropping an Index that is used  by a Foreign Key, Furthermore, when re-applying the Index MySQL complains becuase the key is too long.   This PR reduces the length of the Path to 512 (rather than 1000).
> Fix bug with MySQL Installation caused by new Migration

- Oqtane.Server/Controllers/DatabaseController.cs
- Oqtane.Server/Startup.cs
- Oqtane.Server/appsettings.json
This PR moves the list of available databases to appsettings. While it is not the intention to support additional databases, this provides an option for the enterprising developer to create their own Database project and configure it by updating the settings.
> Move Available Databases to appsettings and use IOptions

- Oqtane.Server/wwwroot/Modules/Templates/External/Server/Controllers/[Module]Controller.cs
The Get public Models.[Module] Get(int id) method in the [Module]Controller has an incorrect IF statement which in turn returns nothing and logs an error
> Fix for #1530 Error in Module templates

- Oqtane.Client/Modules/Admin/Register/Index.razor
Removed the readonly attribute from the username field.
> Fix for  #1555 Username readonly on Register form

- Oqtane.Client/Themes/Controls/Theme/ControlPanel.razor
- Oqtane.Server/wwwroot/Themes/Oqtane.Themes.BlazorTheme/Theme.css
- Oqtane.Server/wwwroot/css/app.css
Offcanvas is a sidebar component that can be toggled on of off
> ConltolPanel to use Bootstrap Offcanvas component

- Oqtane.Client/Modules/Controls/TabPanel.razor
User Management Tab needs clicking to render UI when language is not default.  Modification to the TabPanel fixes the issue without  forcing the Heading property to be populated.
> 1690 User Management Tab needs clicking to render UI when language is not default.

- Oqtane.Server/wwwroot/Modules/Templates/External/Package/release.cmd
One of the replace tokens was not added to the second command line.
> [RootFolder] was missing from Release.cmd

- Oqtane.Client/Themes/OqtaneTheme/Themes/Default.razor
Dropdowns are built on a third party library, Popper, which provides dynamic positioning and viewport detection.  / bootstrap.bundle.js which contains Popper. Popper isn’t used to position dropdowns in navbars though as dynamic positioning isn’t required.
updated the Bootstrap to reference the ../5.1.3/js/bootstrap.bundle.min.js
> Fix for Action Menus not displaying. #1785

- Oqtane.Client/Modules/Admin/ModuleCreator/ModuleInfo.cs
- Oqtane.Client/Modules/HtmlText/ModuleInfo.cs
- Oqtane.Client/Modules/HtmlText/Services/HtmlTextService.cs
- Oqtane.Client/Modules/HtmlText/Services/IHtmlTextService.cs
- Oqtane.Client/Program.cs
- Oqtane.Client/Themes/BlazorTheme/ThemeInfo.cs
- Oqtane.Client/Themes/OqtaneTheme/ThemeInfo.cs
- Oqtane.Server/Infrastructure/SiteTemplates/DefaultSiteTemplate.cs
- Oqtane.Server/Infrastructure/SiteTemplates/EmptySiteTemplate.cs
- Oqtane.Server/Modules/HtmlText/Controllers/HtmlTextController.cs
- Oqtane.Server/Modules/HtmlText/Manager/HtmlTextManager.cs
- Oqtane.Server/Modules/HtmlText/Migrations/01000000_InitializeModule.cs
- Oqtane.Server/Modules/HtmlText/Migrations/EntityBuilders/HtmlTextEntityBuilder.cs
- Oqtane.Server/Modules/HtmlText/Repository/HtmlTextContext.cs
- Oqtane.Server/Modules/HtmlText/Repository/HtmlTextRepository.cs
- Oqtane.Server/Modules/HtmlText/Repository/IHtmlTextRepository.cs
- Oqtane.Server/Program.cs
- Oqtane.Shared/Modules/HtmlText/Models/HtmlText.cs
The docs should help people use the Oqtane API as best as possible. As such, we should hide objects which are just for internal work or won't be used as an API. I've added `[PrivateApi]` attributes to ca. 20 classes which clutter up the docs without real benefit to the user. 
As an example, I've removed tagged all the HtmlText classes, since that's not an API I expect others to need in the docs - this removes these entries from the docs:
+ a few others, all which I'm convinced serve no benefit in the docs. 
Otherwise no code changes.
> Add many PrivateApi attributes to hide unimportant stuff in docs

- Oqtane.Client/Themes/Controls/Theme/Breadcrumbs.razor
This fixes the issue when the page property IsClickable is set to false the breadcrum for the page is not clickable.
> Fix for #1797 Breadcrumbs render clickable

- Oqtane.Client/Themes/Controls/Theme/ControlPanel.razor
When the language is changed, in this instance Dutch the buttons are not resized to fit the caption.  This small fix rectifies this.
**before**
**after**
> Page management buttons resizing

- Oqtane.Client/Modules/Admin/ModuleDefinitions/Index.razor
- Oqtane.Client/Resources/Modules/Admin/ModuleDefinitions/Index.resx
The component now reports back if the module is in use.  This will assist in housekeeping and removal of unused modules.
> Modification to Module Management

- Oqtane.Client/Resources/UI/ModuleInstance.resx
- Oqtane.Client/UI/ModuleInstance.razor
> Implementing ErrorBoundary in ModuleInstance component 

- Oqtane.Client/Modules/Controls/RichTextEditor.razor
Change to the OnAfterRenderAsync method and changed OnInitialized to OnParametersSet
> Fix #1837 RichTextEditor Content not re-Rendering

- Oqtane.Client/Services/Interfaces/ISettingService.cs
- Oqtane.Client/Services/SettingService.cs
- Oqtane.Server/Controllers/SettingController.cs
- Oqtane.Server/Repository/Context/TenantDBContext.cs
Add Update settings for the ModuleDefinition
> Settings for ModuleDefinitions #1829

- Oqtane.Server/Infrastructure/InstallationManager.cs
When a package is remove in some instance the system complains that a file still exists in the deleting directory but there is not file.
Added true parameter to the Directory delete for force the removal. 
Directory.Delete(Path.GetDirectoryName(filepath), true);
> Fix for Installed packages not being removed correctly

- Oqtane.Client/Modules/Controls/RichTextEditor.razor
Restructured the execution of code.
RawHTML now works as it did in previous versions as well as the new functionality.
> Rework to #1848 RawHTML not being saved

- Oqtane.Client/Services/SettingService.cs
Needed to update the SettingService to apply the IsPublic field when updating settings for the ModuleDefinition.
> #1880 Issue with new SettingService

- Oqtane.Client/Modules/ModuleBase.cs
Solve the problem that when the page is rendered for the first time and JS is executed, the reference to the JS file has not been successful, and the page is abnormally wrong
```
An Unexpected Error Has Occurred In DNNGo.Gallery, DNNGo.Gallery.Client.Oqtane: Could not find 'Radzen.preventArrows' ('Radzen' was undefined).
Error: Could not find 'Radzen.preventArrows' ('Radzen' was undefined).
at http://oqtane.dnntest.com/_framework/blazor.server.js:1:497
at Array.forEach (<anonymous>)
at i.findFunction (http://oqtane.dnntest.com/_framework/blazor.server.js:1:465)
at E (http://oqtane.dnntest.com/_framework/blazor.server.js:1:2606)
at http://oqtane.dnntest.com/_framework/blazor.server.js:1:3494
at new Promise (<anonymous>)
at Tt.beginInvokeJSFromDotNet …
```
> Fixed first render js bug

- Oqtane.Client/Modules/ModuleBase.cs
Reverts oqtane/oqtane.framework#1931
This modification breaks JavaScript support and must be reverted
> Revert "Fixed first render js bug"

- Oqtane.Client/Modules/Admin/ModuleDefinitions/Index.razor
The code was assuming that the ModuleDefinitionId exists in the PageState.Modules collection. Instead of using .Count()  code now uses .FirstOrDefault() != null
> Fix for Version 3 module definitions error #1963

- Oqtane.Server/Infrastructure/InstallationManager.cs
Please add support also for `refs` folder in package installation.
My understanding is that Microsoft AspNetCore dependencies that are stored in the "refs" folder are an essential part of the default compilation context to support run-time compilation scenarios in https://github.com/2sic/2sxc/ or any other module or app that targets standard Microsoft.NET.Sdk.Web.
In oqtane source development environment, "refs" are deployed by default when `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` nuget is included as project reference and property `PreserveCompilationContext` is set in `csproj`.
For oqtane release standalone installations, we need to manually deploy "refs" and that is the reason why it will be great to include it as part of 2sxc oqtane module nuget, and that will make life …
> fix #1272 - add support for refs folder in package installation

- Oqtane.Server/Infrastructure/InstallationManager.cs
Oqtane Server **InstallationManager** is extended to recognize and support in nuspec new **file target** `content` that is part of [nuget specification](https://docs.microsoft.com/en-gb/nuget/reference/nuspec#including-content-files).
```xml
<files>
<file src="myconfig.json" target="content" />
</files>
```
The reason is to include in Oqtane Module **nuget** additional content files, that are not stored in `wwwroot` as better explained in https://github.com/oqtane/oqtane.framework/issues/1987.
> fix #1987 Nuspec to include 'content'

- Oqtane.Client/Modules/Admin/Users/Index.razor
- Oqtane.Client/Resources/Modules/Admin/Users/Index.resx
Updated user management to display more of the User ; Last Login Last IP and Is Authenticated.
> Update to User Management 

- Oqtane.Client/Modules/Admin/Users/Index.razor
Added the formatted email address of the user to the list view.
> Added the User Email field to the List

- Oqtane.Client/Resources/Modules/Admin/UserProfile/Index.resx
Updated the Resx File with the missing entries.  
However the UserProfile\Add cant be Localized at present as the IStringLocalizer is not loaded when that property assignment is executed.
> Fix for missing Resx entries #2215

- Oqtane.Client/Resources/SharedResources.resx
without these keys, following module names are not translating,
> missing translation keys for module names

- Oqtane.Server/Controllers/UserController.cs
Audience is passed to GenerateToken instead of Lifetime.
> #Bug in passing Lifetime property to GenerateToken

- Oqtane.Client/Modules/Admin/Jobs/Edit.razor
- Oqtane.Client/Modules/Admin/Jobs/Index.razor
- Oqtane.Server/Infrastructure/Jobs/PurgeJob.cs
- Oqtane.Shared/Shared/Utilities.cs
- Oqtane.Test/Oqtane.Shared.Tests/UtilitiesTests.cs
This is required if using Postgres or you will get an exception with a message of “Cannot write DateTime with Kind=Unspecified to PostgreSQL type 'timestamp with time zone', only UTC is supported.”. #2038
> Make sure Job date times are stored in the database as UTC. 

- Oqtane.Client/Modules/Controls/Pager.razor
This is only when the format is "Table"
Mirrored the Head functionality for <tfoot> tag
> Add footer to the Pager control

- Oqtane.Server/Infrastructure/DatabaseManager.cs
When connection string is specified, result.success == true prevents automatic install to run.
result.Success = true should be set only when everything is ok.
> Unattended installation fix

- Oqtane.Server/Repository/Context/DBContextBase.cs
We have two cases where we need to override the active database:  Unit Testing and added GraphQL.  In both of these cases, we have a database context that is in a different scope than the automatically assigned active database during normal Oqtane startup.  Our work-around has been to make this setter public.  Unless there is a better solution to our cases, I feel this change would be useful for others as well.
> Make ActiveDatabase setter public

- Oqtane.Server/Repository/ModuleDefinitionRepository.cs
Added ISettingRepository _settings  to the public ModuleDefinitionRepository method and updated the DeleteModuleDefinition with _settings.DeleteSettings(EntityNames.ModuleDefinition, moduleDefinitionId);
> Fix for Missing Delete ModuleDefinition settings #1966

- Oqtane.Server/Migrations/EntityBuilders/BaseEntityBuilder.cs
Added AddByteColumn method to BaseEntityBuilder class to generate tinyint field in the database table.
> add AddByteColumn to add tinyint to the database table.

- Oqtane.Server/Oqtane.Server.csproj
extends watching group to include *.dll files and exclude the ones cause an infinite loop.
@sbwalker I need your advice about where I should put the documentation about how to use it.
Hey @vzdesic, could you please help me to finish this as you initiated the issue and provided solution for this.
> extends watching *.dll files

- Oqtane.Server/Controllers/ModuleDefinitionController.cs
We find all Module items that have a ModuleDefinitionName property that matches the ModuleDefinitionName of the item to be removed, and remove them one by one. For each Module item to be removed, we find the PageModule items associated with it, remove them from the pageModules list, and then remove the Module item itself from the modules list.
> Fix for deleting a ModuleDefinition and related records  #2602

- Oqtane.Server/Controllers/ModuleDefinitionController.cs
Added PermissionsRepository to delete the Module permissions when the Module Definition is deleted.
> Fix Correct Permission Delete when ModuleDef is deleted #2619

- Oqtane.Server/wwwroot/Modules/Templates/External/Server/Manager/[Module]Manager.cs
- Oqtane.Server/wwwroot/Modules/Templates/External/Server/Repository/[Module]Context.cs
- Oqtane.Server/wwwroot/Modules/Templates/External/[Owner].[Module].sln
- Oqtane.Server/wwwroot/Themes/Templates/External/Client/Themes/Theme1.razor
- Oqtane.Server/wwwroot/Themes/Templates/External/Client/wwwroot/Themes/[Owner].[Theme]/Theme.css
- Oqtane.Server/wwwroot/Themes/Templates/External/[Owner].[Theme].sln
Dev Branch Module and Theme Template Build Fix
Fixes #2627
Fixes #2631
Fixes #2630
Fixes #2629
Fixes #2632
Fixes #2635
> Fixes #2627 #2631 #2630 #2629 #2632  #2635 - Dev Branch Module and Theme Template Issues

- Oqtane.Client/Modules/Admin/Register/Index.razor
- Oqtane.Client/Resources/Modules/Admin/Register/Index.resx
Generating a password can generate a lot of errors and leading to frustration when trying to Register on an Oqtane site.  This is manly due to the visitor not knowing the Password Requirements.  This has been addressed in this PR.
The Password requirements are now displayed to the visitor.
> Modified Registration to display the Password requirments

- Oqtane.Server/Repository/PermissionRepository.cs
Permissions for Role Name is null causing child sites to fail to load creating an exception error. #2724 
I tried to clear cache in other areas like at the top of GetPermissions and LoadModuleDefnitions however did not resolve the issue of trying to access sites created from the master site.
This fix presented in this PR should... allow Oqtane to continue to run while accessing alias sites.
This is probably not the fix as I seen errors now in the event log for the site:
Unauthorized Folder Get Attempt {Path} For Site {SiteId}
however I logged out and back in and no error.
But then after browsing user profile I would get notification errors popping up 
`Log Message: Unauthorized Folder Get Attempt Users\1\ For Site 2`
So need further testing.  This probably should not be returning a null …
> Fixes null reference permissions issue: Fixes #2724 

- Oqtane.Client/Themes/Controls/Theme/MenuHorizontal.razor
Add the css class to MenuHorizontal to handle scrolling when hamburger Menu is in use.
> Fix for MenuHorizontal #2757

- Oqtane.Client/Resources/SharedResources.resx
This PR simply adds some very common new language translation values to Oqtane Framework` SharedResources.rex` file to help developers and site administrators have one common shared place to edit these very common types of key values.
This should not introduce a breaking change however if you feel it will I understand and we can close the issue and PR.
Thank you.
Fixes #2732
> Add support for new language translation values for #2732.

- Oqtane.Client/Modules/Admin/Dashboard/Index.razor
This pr updates dashboard index SecurityAccessLevel to match other module pages.  Clarity here maybe needed to understand this override.
I set this to Admin and tested all scenarios where you may have another role with a registered user manage admin/roles and everything worked as expected.
> Updated Dashboard Index

- azuredeploy.json
I have made the SQL Server database and the AppServices which is provisioned to be basic tier as per your suggestion by @sbwalker
> Made the default SQL Server and App Service provisioned Basic Tier

- Oqtane.Server/Controllers/SiteController.cs
- Oqtane.Server/wwwroot/Themes/Templates/External/Client/Containers/Container1.razor
- Oqtane.Server/wwwroot/Themes/Templates/External/Client/Containers/ContainerSettings.razor
- Oqtane.Server/wwwroot/Themes/Templates/External/Client/ThemeInfo.cs
- Oqtane.Server/wwwroot/Themes/Templates/External/Client/Themes/Theme1.razor
- Oqtane.Server/wwwroot/Themes/Templates/External/Client/Themes/ThemeSettings.razor
- Oqtane.Server/wwwroot/Themes/Templates/External/Client/_Imports.razor
- Oqtane.Server/wwwroot/Themes/Templates/External/[Owner].Theme.[Theme].sln
Added ThemeSettings and ContainerSettings to Default Theme Template to Demonstrate how these features could be added to developers designing a theme as requested and discussed in Issue #2633
> Added ThemeSettings and ContainerSettings to Default Theme Template

- Oqtane.Server/wwwroot/Modules/Templates/External/Client/Modules/[Owner].Module.[Module]/Settings.razor
changed 
`private string resourceType = "[Owner].[Module].Settings, [Owner].[Module].Client.Oqtane"; // for localization`
to 
`private string resourceType = "[Owner].Module.[Module].Settings, [Owner].Module.[Module].Client.Oqtane"; // for localization`
to match the correct NameSpace
> [FIX] - Fixed the ResourceType in Module Settings with correct NameSpace

- Oqtane.Server/wwwroot/Modules/Templates/External/[Owner].Module.[Module].sln
Removed Oqtane. Server build from configuration manager debug and release.
> Fix for #2983 Oqtane. Server selected in for build in configmanager

- Oqtane.Server/Controllers/PageController.cs
> Fixing personalized page created to be UserName if DisplayName is null

- Oqtane.Client/Modules/Admin/Pages/Add.razor
- Oqtane.Client/Modules/Admin/Pages/Edit.razor
- Oqtane.Server/Infrastructure/Interfaces/IHostResources.cs
Found a small typo what would limit the theme dropdowns on page add/edits to show only the default theme.
> Show all themes on page add/edit

- Oqtane.Client/Themes/Controls/Container/ModuleActionsBase.cs
The Publish Method was Publishing the Page instead of the Module which were removing permissions
Fix for #3033
> [FIX] - Page disappears if you unpublish and publish a module

- Oqtane.Client/Modules/Controls/AutoComplete.razor
The control now allows the required attribute to be set.  This will now give better UX feedback.
> Extended AutoComplete control to allow the Required attribute

- Oqtane.Client/Modules/Admin/Files/Edit.razor
- Oqtane.Client/Modules/Admin/Jobs/Index.razor
- Oqtane.Client/Modules/Admin/Languages/Add.razor
- Oqtane.Client/Modules/Admin/ModuleDefinitions/Add.razor
- Oqtane.Client/Modules/Admin/Pages/Add.razor
- Oqtane.Client/Modules/Admin/Pages/Edit.razor
- Oqtane.Client/Modules/Admin/RecycleBin/Index.razor
- Oqtane.Client/Modules/Admin/Site/Index.razor
- Oqtane.Client/Modules/Admin/Themes/Edit.razor
- Oqtane.Client/Modules/Admin/Upgrade/Index.razor
- Oqtane.Client/Resources/Modules/Admin/Files/Add.resx
- Oqtane.Client/Resources/Modules/Admin/Files/Edit.resx
- Oqtane.Client/Resources/Modules/Admin/Jobs/Index.resx
- Oqtane.Client/Resources/Modules/Admin/ModuleDefinitions/Add.resx
- Oqtane.Client/Resources/Modules/Admin/Pages/Add.resx
- Oqtane.Client/Resources/Modules/Admin/Upgrade/Index.resx
- Oqtane.Client/Resources/SharedResources.resx
Updated the Missing or incorrect keys
> Translation for thread #3094

- Oqtane.Client/Modules/ModuleBase.cs
Anonymous Object are not able to be used across assemblies however ExpandoObject is refer to #3145
> [ENHANCE] - Change to ExpandoObject instead of an Anonymous Object

- Oqtane.Client/Installer/Controls/MySQLConfig.razor
- Oqtane.Client/Installer/Controls/PostgreSQLConfig.razor
- Oqtane.Client/Installer/Controls/SqlServerConfig.razor
Updated Mysql, Postgresql & Sqlserver Installer Controls to hide/show db password.
The ideal would be to have a ShowPassword component, but in the mean time I used the same code from the Main Installer.
> Update database installers to show/hide passwd

- Oqtane.Client/Modules/Admin/Pages/Add.razor
- Oqtane.Client/Modules/Admin/Pages/Edit.razor
- Oqtane.Client/Modules/Controls/InputList.razor
The control accepts a dictionary of string that can be searched using an input control.
Pages Add and Edit have implemented the control to render the list of Icons found in the Oqtane Shared namespace.
> Add InputList control to select values from a dictionary of string

- Oqtane.Server/wwwroot/Themes/Templates/External/Client/wwwroot/Themes/[Owner].Theme.[Theme]/Theme.css
This PR should resolve #3278 
This basically inverts the color from the background but this value can be changed on the selected element for child pages as needed.  I believe this selector should do the trick so we can at least see the child pages from the Oqtane default theme creator template.
> Updates Child Page Link Color in Theme Creator Template - Theme.css - Fixes #3278

- Oqtane.Client/Modules/Admin/Users/Index.razor
- Oqtane.Client/Resources/Modules/Admin/Users/Index.resx
The logic for including this additional column is that the search functionality allows you to search on Username, DisplayName and Email.  However, only the Username and DisplayName columns are displayed, so you don't have direct confirmation of the email search match.  Additionally, looking up emails is one of the most used reasons that admins go to the User Manager screen.
> Add Email column to User Manager screen

- Oqtane.Client/Themes/Controls/Theme/LanguageSwitcher.razor
When the LanguageSwitcher is dsiplayed the wsa no end padding on the button so it appeared flush with the following button.  Adding "pe-1" to the class corrects the issue
> upated LanguageSwitcher with end padding

- Oqtane.Client/Modules/Admin/Pages/Edit.razor
without this check, admin dashboard -> Page Management -> Edit page is crashing
> Empty _themetype check to avoid page crash

- Oqtane.Client/Services/SyncService.cs
I fixed issue #3282
This problem occurred in some calendars, including the Persian calendar
> Fixed issue #3282

- Oqtane.Client/Modules/Admin/Users/Index.razor
- Oqtane.Client/Resources/Modules/Admin/Users/Index.resx
- Oqtane.Server/Extensions/OqtaneSiteAuthenticationBuilderExtensions.cs
Introduce a dropdown menu in the 'External Login' settings area for authentication flow response types. 
I used the response types found in the Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectResponseType class.
For more information take a look at: #3325
> Introduce a dropdown menu for authorization response types

- Oqtane.Client/Themes/BlazorTheme/Themes/Default.razor
- Oqtane.Client/Themes/Controls/Theme/ControlPanel.razor
- Oqtane.Client/Themes/Controls/Theme/LanguageSwitcher.razor
- Oqtane.Client/Themes/OqtaneTheme/Themes/Default.razor
> Language Selector Alignment fix  #3368

- Oqtane.Client/Modules/Admin/ModuleDefinitions/Create.razor
Modified the Regex to all punctuation in the description. "^[A-Za-z0-9 .,!?]+$")
> Module Creator allow punctuation in Description field

- Oqtane.Client/Modules/Admin/UserProfile/Index.razor
- Oqtane.Client/Resources/Modules/Admin/UserProfile/Index.resx
This PR resolves two issues:
- notification action buttons column formatting
- add a message of no notifications for users inbox or sent items.
- adds localization to no notifications messages.
- adds class wrapper around no notifications localization text
Fixes #3413
Fixes #3415
Since these issues relate to same file both issues are handled in this single PR
Formatting of the columns properly is more complicated than adding this "no notifications" message which is why I went ahead and included it here as it also makes sense to have it as an enhancement.
Should not introduce any breaking changes, all CSS styles should apply.
> UserProfile/Index.razor: Notifications Formatting and No Notifications Message - Fixes #3413, #3415

- Oqtane.Client/Modules/Admin/Login/Index.razor
- Oqtane.Client/Themes/Controls/Theme/LoginBase.cs
this logoic was mistakenly refactored in #3319 which resulted in an infinite loop in the scenario where External Login is enabled, Site Login is disabled, and a user clicks a link from their "External Login Linkage" email
> if site login is disabled redirect Login to external identity provider

- Oqtane.Client/Modules/Admin/Users/Index.razor
- Oqtane.Client/Resources/Modules/Admin/Users/Index.resx
- Oqtane.Server/Extensions/OqtaneSiteAuthenticationBuilderExtensions.cs
This option can be disabled in environments that have a trusted IDP and would like to bypass the External Login Linkage verification step for their registered users. The default is True (meaning that verification is enabled).
> added Verify Existing Users? option to User Management - External Login Setting

- Oqtane.Client/Modules/Admin/Profiles/Edit.razor
- Oqtane.Client/Resources/Modules/Admin/Profiles/Edit.resx
Fixes #3426 
Fixes #3446
Updates Admin\Profiles\Edit.razor:
- Adds form validation for Rows, Length and Order form input to Profiles\Edit.razor component` type="number"`.
- Adds form validation for Rows `min="1"`.
- Replaces the ignored `maxLength` attribute with `max` attribute for inputs with type attribute as number.
- Adds `Rows` resource data to related Profiles\Edit.resx file.
> Admin\Profiles\Edit.razor: Form Validation For Rows, Length and Order - Adds Rows Resource Data - Issues #3426,  #3446

- Oqtane.Client/Modules/Admin/Login/Index.razor
- Oqtane.Client/Modules/Admin/Users/Index.razor
- Oqtane.Server/Extensions/OqtaneSiteAuthenticationBuilderExtensions.cs
Added functinality to always remember user login. Provides the option to force login cookie expiration and dont fallback on the session timespan that is used as default when users dont choose the option 'Remember me'.
Added login cookie expiration time. Added setting in user settings to declare custom cookie expiration time. Cookie expiration time overwrites default expiration time of 14 days (if not session timespan is used).
These settings are optional.
Background info: We use oqtane as a framework that hosts our angular applications. The angular applications use a login system with login cookie expiration of 8 hours. Oqtane uses cookie session timespan. So when the login cookies in our application run out oqtane might still be logged in, which causes incompatibility between our …
> Added login cookie expiration time functionality.

- Oqtane.Server/Pages/_Host.cshtml.cs
Noticed some spaces showing up in theme resources and tracked it down to this line.  Wrapping the name in a call to Utilities.GetTypeName cleared things up.
> Update _Host.cshtml.cs to account for fully qualified type names in theme resources 

- Oqtane.Client/Modules/Admin/Site/Index.razor
- Oqtane.Client/Modules/Admin/Sites/Add.razor
a dedicated option should be added  to enable Blazor Hybrid
> remove Blazor Hybrid from Hosting Models selection as it is not actually a hosting model

- Oqtane.Client/Modules/Admin/Jobs/Edit.razor
- Oqtane.Client/Modules/Admin/Logs/Index.razor
- Oqtane.Client/Modules/Admin/Site/Index.razor
- Oqtane.Client/Modules/Admin/Visitors/Index.razor
The Retention input controls in Log, Visitors and Notifications allowed text to be saved.  Modified all controls to accept only number.
> Retention controls and data should be number / int not string

- Oqtane.Client/Modules/Admin/Languages/Add.razor
- Oqtane.Client/Modules/Admin/Languages/Edit.razor
- Oqtane.Client/Modules/Admin/Languages/Index.razor
- Oqtane.Client/Resources/Modules/Admin/Languages/Edit.resx
- Oqtane.Client/Services/Interfaces/ILanguageService.cs
- Oqtane.Client/Services/LanguageService.cs
- Oqtane.Server/Controllers/LanguageController.cs
- Oqtane.Server/Repository/Interfaces/ILanguageRepository.cs
- Oqtane.Server/Repository/LanguageRepository.cs
Currently the Languages module allows to set the default language only when Adding a new Language. This pull request adds and additional edit button if the language is not the default one. On click, the edit button presents an edit windows, similar to the Add Language but without download capabilities. It allows to change only the default checkbox.
> Edit languages to set default.

- Oqtane.Server/wwwroot/Themes/Oqtane.Themes.OqtaneTheme/Theme.css
- Oqtane.Server/wwwroot/Themes/Templates/External/Client/wwwroot/Themes/[Owner].Theme.[Theme]/Theme.css
- Oqtane.Server/wwwroot/css/app.css
Fixes #3571 
Sets Logo max height to 90px plus padding 5px right and left.
If even 150px it will cover up content in the admin pages and other places.
It would be worth considering creating variables that adjust logo and content margins.  I set this in the app.css at the top since it is the logo image first thing you see when loading app.  I had also thought this could go in the Oqtane Theme.css however .app-logo is part of the app.  I can produce another PR if this should be in the Oqtane theme.css instead.
I can also explore creating variables that can adjust according to the image height uploaded which was another idea I had but would take more investigating that possibility.
> Sets Logo max height to 90px plus padding 5px right and left.

- Oqtane.Client/Modules/Admin/Site/Index.razor
Fixes: #3582
This PR will simply refreshes the current page in order to view the change of the updated logo.
This is only performed when a logo file id has changed from original loaded on the page it gets on initialization from `logofileid `and compares it with` _logofileid` which is are used for different areas of code logic.  I originally had a new variable set to know it was the original but found one that would serve the same purpose not being used or reset to compare with the one that was updated from the file manager component. 
This all relates to the site settings component during Oqtane administration when a user changes the logo and performs the save button action.
I had a few other "NavigationManager" version to refresh, this one used in commit seemed so simple I used it.
After …
> Refreshes Admin Settings Page When User Updates Logo.  Fixes #3582

- Oqtane.Client/Modules/ModuleBase.cs
Fixes #3599
This PR updates the AddModuleMessage() UI method in the ModuleBase.cs file logic to clear the module message prior to displaying one in the event one already exists or was dismissed previously.
> Clear Module Message Prior To Adding A Message To UI. Fixes #3599

- Oqtane.Client/Modules/HtmlText/Index.razor
- Oqtane.Client/Modules/ModuleBase.cs
- Oqtane.Client/Themes/ContainerBase.cs
- Oqtane.Client/UI/ContainerBuilder.razor
- Oqtane.Client/UI/ModuleInstance.razor
- Oqtane.Client/UI/PageState.cs
- Oqtane.Client/UI/Pane.razor
- Oqtane.Client/UI/SiteRouter.razor
- Oqtane.Shared/Models/Module.cs
this PR introduces a RenderId (GUID) which serves as a unique identifier to detect when a change has occurred to PageState. It is used within the ShouldRender method on components to prevent unnecessary rendering and as a flag to suppress other types of component processing
> improved rendering optimization

- Oqtane.Client/Modules/Admin/Profiles/Edit.razor
Prior functionality allowed 4 characters for "order" which now causes validation errors for any order value > 99.  This change allows a value of up to 9999 which is consistent with the prior 4 character length value.
Prior functionality allowed 2 characters for "rows" which now causes validattion error for any row count > 10.  This change allows a value up to 99 which is consistent with the prior 2 character length value.
> Update Oqtane.Client\Modules\Admin\Profiles\Edit.razor to fix breaking changes

- README.md
Fixes #3607 
This adds an icon using github icons (maybe we can make our own later) next to the Deploy To Azure button that links to the marketplace and adds a section to the README file that introduces that Marketplace with a link.
Of course had to play with the markdown for a bit in  GitHub Editor to see what would potentially make this PR acceptable.
And choice of words is optional here as "Visit" "Explore" "Discover" can all be used, but this current pr gives a trifecta approach hitting all three in the words in the first two sentences, then the link.  But if you want a little more weight one way or another there is this to overthink.
> README - adds marketplace information for issue #3607 

- README.md
Fixes #3627, can also help resolve issues relating to #3595
Fixes #3627
Clarify Getting Started Instructions by breaking down each step and making an important step to build prior to the last step running the project.
Acceptable solution here will need to be updated in https://github.com/oqtane/oqtane.docs/issues/20 as well for these instructions to be updated.
This should help with some build issues being reported.  I suggest reviewing the blog instructions and approaching it the same way. 
Can we put [Download dev branch](https://codeload.github.com/oqtane/oqtane.framework/zip/refs/heads/dev) link for that part of the getting started instruction guide?
> Clarify Getting Started Instructions. Fixes #3627

- Oqtane.Client/Oqtane.Client.csproj
- Oqtane.Database.PostgreSQL/Oqtane.Database.PostgreSQL.csproj
- Oqtane.Database.SqlServer/Oqtane.Database.SqlServer.csproj
- Oqtane.Database.Sqlite/Oqtane.Database.Sqlite.csproj
- Oqtane.Maui/Oqtane.Maui.csproj
- Oqtane.Server/Oqtane.Server.csproj
- Oqtane.Shared/Oqtane.Shared.csproj
This PR includes routine maintenance to upgrade the NuGet packages used in the Oqtane Framework. All projects build successfully post-upgrade using today's updated version of Visual Studio 2022. This is done in anticipation of the 5.0.2 release. Developers are encouraged to test these changes to ensure no issues arise from the package upgrades.
> Upgrade NuGet Packages for Oqtane Framework

- Oqtane.Server/Controllers/FileController.cs
Fixes #3646
- Added check for null or empty `formfile` in `UploadFile()` method located in `FileController.cs`
> Handle null or empty formfile in UploadFile Method - Fixes #3646

- Oqtane.Maui/wwwroot/js/interop.js
- Oqtane.Server/wwwroot/js/interop.js
This pull request simply updates the XLMHttpRequest to use `statusText` to provide a more helpful message of the request status instead of `status` which provides a number for the status.
> Updates request.status to request.statusText in Interop.js

- Oqtane.Client/Modules/Admin/ModuleDefinitions/Create.razor
- Oqtane.Client/Resources/Modules/Admin/ModuleDefinitions/Create.resx
Fixes #3597
This PR adds the information to the help text and notification to not use module owner or names that contain the word "oqtane".
It should help resolve issues as shown in #3597 while trying to create a module with a module name that contains "Oqtane" word in it.
This would need to be edited to inform the module name and owner is not allowed to start with the word "Oqtane" if current modifications being tested allow this without experiencing namespace conflicts in the framework itself.  This is being discussed in #3597 
Additional Context Relating To Documentation:
Another option to help enhance on-boarding module creators in this area is to have a link to Oqtane Module Creator Documentation for additional online support.  I have an [enhanced documentation …
> Module Creator Owner/Name + Notification Help Text Includes Warning Not To Use The Word "Oqtane".  Fixes #3597

- Oqtane.Client/Installer/Installer.razor
- Oqtane.Client/Modules/Admin/Profiles/Edit.razor
- Oqtane.Client/Modules/Admin/Register/Index.razor
- Oqtane.Client/Modules/Admin/UserProfile/Index.razor
- Oqtane.Client/Resources/Modules/Admin/Profiles/Edit.resx
- Oqtane.Server/Migrations/Tenant/05010003_AddProfileAutocomplete.cs
- Oqtane.Shared/Models/Profile.cs
This PR implements the enhancement proposed in issue #[Issue_Number]: [Link to Enhancement Issue]
- Added a new setting or property to profile properties to control the `autocomplete` attribute.
- Implemented the logic to conditionally include the `autocomplete` attribute based on the new setting.
- Also Adds the Autocomplete attribute for "name" and "email" to the user profile account tab input elements.
Closes #3651 
1. Visit Profile Management
2. Add text to the autocomplete input
3. Visit your profile and view the source to see the autocomplete attributed added only if you have it set.  Blank will not generate the autocomplete attribute.
I can set some default autocomplete settings for the default profile properties, or this can be done later or leave it to admins.
The order of where …
> Enh: Autocomplete Attribute Enhancement

- Oqtane.Server/wwwroot/Themes/Oqtane.Themes.OqtaneTheme/Theme.css
#3692 adds an unnecessary space when adding the semi-colon to the width.
This pull request removes that space from the theme.css file.
> Removed unintended space added from PR #3692.

- Oqtane.Maui/Oqtane.Maui.csproj
Fixes #3758
Updates Oqtane.Maui packages to the latest versions available.
I noticed when updating these I was also given another package:
```
<ItemGroup>
<PackageReference Update="Microsoft.Maui.Controls.Compatibility" Version="8.0.6" />
</ItemGroup>
```
I went ahead an added    ` <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.6" />` to avoid needing to perform an update to get this included package to latest version.
> Fixes #3758 Updates Referenced Maui Packages To Latest

- Oqtane.Maui/Head.razor
Closes #3753
This PR updates Oqtane.Maui namespace used for the dynamic component type utilizing the Head.razor component to reflect it's recent namespace change introduced during version 5.0.3 updates.
> Oqtane.Maui - Updates To New Namespace For DynamicComponent Type Oqtane.UI.Head - Fixes #3753

- Oqtane.Client/Services/Interfaces/IModuleDefinitionService.cs
- Oqtane.Client/Services/ModuleDefinitionService.cs
This pull request cleans up unused namespaces in the Oqtane.Client project `Services\ModuleDefinitionService.cs` and `Services\Interfaces\IModuleDefinitionService.cs` files.
Oqtane Framework was able to build and run as expected after these namespaces where removed with the related functionality behavior being reviewed.
Before:
After:
Testing:
There is no issue related as this is just maintenance.  Trying to keep each of these limited similar pull requests separated and spread out over time to be sure nothing comes unexpectedly.  If something is an issue can can be more easily identified this way as well.  I will try to limit these type of pull requests to 1 maybe 2 per release since they are not mission critical.  More or less some house cleaning.
I can clean up a couple more files in …
> Cleanup module definitition service namespaces

- Oqtane.Client/Services/Interfaces/IPageService.cs
Since this is a simple documentation spelling correction I don't believe there is need for an issue.
This pull request corrects a spelling error in documentation comments adding an "r" character to complete the word "Returns" in the Oqtane.Client IPageServices.cs interface.
> Corrects documentation spelling error for the word "Returns" in IPageService.cs

- Oqtane.Client/Themes/Controls/Theme/LoginBase.cs
Fixes #3766
This change ensures that the login URL construction in the `LoginBase` class properly includes the `login` route when appropriate. Previously, the login URL was missing the "login" part, leading to incorrect navigation behavior. By using `+=` instead of `=`, we preserve the login button control appended "login" route to the existing return URL, resolving the issue.
> Ensure "login" route is included in login URL construction. Fixes #3766

- Oqtane.Client/Themes/Controls/Theme/UserProfile.razor
This pull request fixes the handling of the returnurl parameter in the UserProfile component. Previously, the returnurl parameter was being incorrectly appended multiple times in the URL, leading to unintended behavior. The issue has been addressed by properly checking for the existence of the returnurl parameter and appending it only once if necessary.
Changes Made:
- Modified the `OnParametersSet` method in the `UserProfile` UI control component to handle the `returnurl` parameter correctly
- Ensured that the returnurl parameter is appended only once, preventing duplication in the URL
Resolves: #3825
> Fix handling of returnurl parameter in UserProfile component - Fixes #3825

- Oqtane.Client/Modules/Admin/Login/Index.razor
- Oqtane.Client/Modules/Admin/Register/Index.razor
- Oqtane.Client/Resources/Modules/Admin/Login/Index.resx
- Oqtane.Client/Resources/Modules/Admin/Register/Index.resx
added links from login to register and vice versa as the theme doesn't have to provide these links
> added links from login to register and vice versa

- Oqtane.Server/wwwroot/Themes/Oqtane.Themes.BlazorTheme/Theme.css
- Oqtane.Server/wwwroot/Themes/Oqtane.Themes.OqtaneTheme/Theme.css
- Oqtane.Server/wwwroot/Themes/Templates/External/Client/wwwroot/Themes/[Owner].Theme.[Theme]/Theme.css
Closes #3762
This PR will set the break point for all CSS themes and theme creator to bootstrap md max-width of 767.98px.
> Sets responsive breakpoint match 767.98px = Bootstrap md - Fixes #3762

- Oqtane.Client/Themes/OqtaneTheme/ThemeInfo.cs
- Oqtane.Server/wwwroot/Themes/Templates/External/Client/ThemeInfo.cs
This pull request updates bootstrap and bootswatch to latest versions without breaking any UI styles or controls like previous attempt.
Closes #3772 
As far as styling goes, it seems to present things as intended.
Functionality is limited on some UI components with static SSR enabled, but no styling issues with Theme Creator or Oqtane themes.
I did find an issue possibly with the ThemeCreator project with ModuleInstance I commented out to get past quickly.
I will test this more to see if it is a bug or something just in my environment at the time.
I will test functionality against the current dev repository to see if any issues need reopened.  I sometimes forget to set the new installs to static SSR and may think something is fixed as I need to be sure to double check this setting while …
> Updates theme bootstrap and bootswatch to version 5.3.2 - closes #3772

- Oqtane.Client/Modules/Admin/Site/Index.razor
Fixes #3863
This pull request updates the SaveSite() method removing the reload/refresh logic and forcing always a reload when Site Settings are saved.
Additional logic checks can be removed and filtered through on an additional commit.
> Fixes #3863 - Site Settings: Always reload the page on SaveSite()

- Oqtane.Client/Themes/BlazorTheme/Themes/Default.razor
Additional fix for #3772
This pull request will update the Blazor theme bootstrap to version 5.3.2.
> Updates Blazor Theme Bootstrap to Version 5.3.2

- Oqtane.Server/Oqtane.Server.csproj
This pull request is not related to any issue and only updates the `Oqtane.Server` project file package dependency `Microsoft.AspNetCore.Authentication.OpenIdConnect` to version `8.0.2` in the `dev` 5.1.0 branch.
> Updates Microsoft.AspNetCore.Authentication.OpenIdConnect To Version 8.0.2

- Oqtane.Server/wwwroot/Themes/Templates/External/Client/Resources/[Owner].Theme.[Theme]/Container.resx
- Oqtane.Server/wwwroot/Themes/Templates/External/Client/Resources/[Owner].Theme.[Theme]/ContainerSettings.resx
- Oqtane.Server/wwwroot/Themes/Templates/External/Client/Resources/[Owner].Theme.[Theme]/Theme.resx
- Oqtane.Server/wwwroot/Themes/Templates/External/Client/Resources/[Owner].Theme.[Theme]/ThemeSettings.resx
Currently the template uses the Localization Resource functionality but it will always default to the hardcoded text.  Leaving it to the developer to add the resources could result in a hit and miss scenario. This PR removes the "mis" side.
> Added Resource Files to Theme Templates

- Oqtane.Client/Modules/Admin/Login/Index.razor
How to reproduce:
1- set the site render mode to blazor web assembly
2- register as new user 
3- Open the email verification link 
result:
Error : System.AggregateException: One or more errors occurred. (ElementReference has not been configured correctly.)
---> System.InvalidOperationException: ElementReference has not been configured correctly.
at Microsoft.AspNetCore.Components.ElementReferenceExtensions.GetJSRuntime(ElementReference elementReference)
at Microsoft.AspNetCore.Components.ElementReferenceExtensions.FocusAsync(ElementReference elementReference, Boolean preventScroll)
at Microsoft.AspNetCore.Components.ElementReferenceExtensions.FocusAsync(ElementReference elementReference)
at Oqtane.Modules.Admin.Login.Index.OnAfterRenderAsync(Boolean firstRender) in …
> handle focus error on blazor web assembly when verifying email address

- Oqtane.Client/Modules/Admin/Files/Index.razor
- Oqtane.Client/Modules/Admin/Logs/Index.razor
- Oqtane.Client/Modules/Admin/ModuleDefinitions/Index.razor
- Oqtane.Client/Modules/Admin/Themes/Index.razor
- Oqtane.Client/Modules/HtmlText/Index.razor
This reverts commit 92719d095a700675f2b869450ec299f457321452.
> Revert "removed AddModuleMessage from OnParametersSetAsync methods to mitigate risk of infinite loops"

- Oqtane.Server/Extensions/ApplicationBuilderExtensions.cs
- Oqtane.Server/Infrastructure/Middleware/ExceptionMiddleware.cs
- Oqtane.Server/Startup.cs
added exception middlware to log server exceptions
> added exception middleware to server for logging

- Oqtane.Client/Modules/Controls/Pager.razor
This pull request enhances the behavior of the search input text field by disabling the browser’s autocomplete feature. Here’s why I’ve opted for the <form> tag approach:
**Form-Level Control:**
By placing autocomplete="off" on the <form> tag, we ensure consistent behavior across all input fields within the form. Although only one field, adding it to the Input control gives strange effects across browsers.
**Edge Compatibility:**
As mentioned earlier, Edge 18 has limited support for autocomplete="off".
By setting it at the form level, we address this issue globally for all browsers, including Edge.
**Why This Matters:**
Improved user experience: Users won’t be distracted by irrelevant autofill suggestions.
Consistency: The search input field now behaves uniformly across browsers.
**Note …
>  Improved Pager Search Input Text Field Autocomplete Behavior

- Oqtane.Server/Oqtane.Server.csproj
I have spoken to the maintainer of ImageSharp:
"If a user downloads Oqtane, the version of ImageSharp bundled with Oqtane is licensed to the user under the terms of the Apache 2.0 license as that was the license Oqtane consumes the library under. This means their consumption is transitive ie. they have the right to use ImageSharp under the Apache 2.0 license as long as it is used in conjunction with Oqtane. If the user downloads a version of ImageSharp that replaces the version bundled with Oqtane then their consumption becomes direct and they are subject to the terms of the license. "
So this means ImageSharp can be safely upgraded to the latest version without any licensing concerns - as Oqtane is able to include it under the Apache 2.0 license (which is compatible with the MIT license …
> updating ImageSharp to latest

- Oqtane.Client/Modules/Controls/ActionLink.razor
if (IconOnly && !string.IsNullOrEmpty(IconName)) was not having an impact as the _text variable was being reset.
This fix allows the ActionLink to display just the Icon
> _text being set and resetting other options

- Oqtane.Client/Oqtane.Client.csproj
- Oqtane.Database.PostgreSQL/Oqtane.Database.PostgreSQL.csproj
- Oqtane.Database.SqlServer/Oqtane.Database.SqlServer.csproj
- Oqtane.Database.Sqlite/Oqtane.Database.Sqlite.csproj
- Oqtane.Maui/Oqtane.Maui.csproj
- Oqtane.Server/Oqtane.Server.csproj
- Oqtane.Shared/Oqtane.Shared.csproj
Fixes #3991
Updates to latest relating 8.0.3 package references as shown in the following files:
```
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.3" />
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="8.0.3" />
<PackageReference Include="Microsoft.Extensions.Localization" Version="8.0.3" />
```
```
<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.3" />
```
```
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.3" />
```
```
<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.3" />
```
```
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.3" />
<PackageReference …
```
> Fix #3991: Updates Package Dependencies In Project Files To Relating Current Versions For 8.0.3 Release

- Oqtane.Server/Components/App.razor
Fixes #4062
Moves resources loading in the body of `App.razor` file above loading the `blazor.web.js`
> Fixes #4062: App.razor - moves loading body resources above blazor.web.js

- Oqtane.Client/Services/ProfileService.cs
ProfileService was passing SiteId instead of ProfileId which was causing updates to profile entries to fail with "Unauthorized Profile Put Attempt".
> Fix incorrect parameter passed from ProfileService to ProfileController

- Oqtane.Client/Services/VisitorService.cs
- Oqtane.Server/Controllers/VisitorController.cs
Version - 5.1.1
Render Mode - Static 
Interactivity - Server
Database - SQL Server
When transitioning to visitor management in the Japanese location, an application error occurs.
[Event Log]
It is believed that an error will always occur when transitioning to Visitor Management in locations that use multibyte characters.
> Datetime formatting issue

- Oqtane.Client/UI/RenderModeBoundary.razor
previously it was reporting the ModuleState.RenderMode which is not always the actual render mode used at runtime (ie. it depends on the Site Setting)
> fix HTML comment to indicate actual RenderMode for component (including Interactivity)

- Oqtane.Client/Themes/Controls/Theme/ControlPanel.razor
- Oqtane.Client/Themes/Controls/Theme/LanguageSwitcher.razor
This change allows the buttons to be uniform.
> LanguageSwitcher to use the ButtonClass parameter

- Oqtane.Client/Modules/Admin/Pages/Edit.razor
- Oqtane.Client/UI/SiteRouter.razor
- Oqtane.Server/Components/App.razor
int.Parse("-1") throws  FormatException for cultures other than English (en-US)
> Format Exception in int.Parse(route.ModuleId)

- Oqtane.Client/Resources/Themes/Controls/ControlPanelInteractive.resx
- Oqtane.Client/Themes/Controls/Theme/ControlPanelInteractive.razor
Fix #4030: add copy module option for add existing module function.
> Fix #4030: add copy module option for add existing module function.

- Oqtane.Client/Resources/Themes/Controls/ControlPanelInteractive.resx
- Oqtane.Client/Themes/Controls/Theme/ControlPanelInteractive.razor
- Oqtane.Server/Modules/HtmlText/Manager/HtmlTextManager.cs
- based on usability testing changed approach to filter the list of modules to those which support IPortable
- removed RESX keys which are not used
- fixed issue related to spelling mistake ```if (_moduleType == "exsiting.copy")```
- fixed issue in Html/Text module export which was not exporting the latest content version
> refactor #4198 - copy existing module

- Oqtane.Client/Modules/Admin/Modules/Settings.razor
- Oqtane.Client/Modules/Admin/Roles/Index.razor
- Oqtane.Client/Modules/Admin/UrlMappings/Index.razor
- Oqtane.Client/Resources/Modules/Admin/UrlMappings/Index.resx
- Oqtane.Client/Resources/Themes/Controls/ModuleActionsBase.resx
- Oqtane.Client/Themes/Controls/Container/ModuleActionsBase.cs
Fix for missing parameters and Resx values Issue #4202 Issue #4203
> Fix for missing parameters and Resx values Issue #4202 #4203 #4210 and part #4209

- Oqtane.Shared/Shared/Utilities.cs
Added null or empty check for the content and alias parameters at the beginning of the method.
> Null or empty check for FormatContent

- Oqtane.Client/Modules/Controls/ActionDialog.razor
Just like ActionLink, ActionDialog should support displaying its open button with only an icon to be able to design tables with columns such as:
While still maintaining the text and icon in the action button inside the modal:
> [ENH] Support for IconOnly in ActionDialog open button

- Oqtane.Client/Modules/Admin/Modules/Settings.razor
removed the override string Title as it will be set Localized in the OnInitialized using SetModuleTitle base method.
> Fix for #4259 Localizer Null in Module Settings

- Oqtane.Client/Modules/Controls/ModuleMessage.razor
- Oqtane.Client/Modules/ModuleBase.cs
- Oqtane.Client/UI/RenderModeBoundary.razor
Fix #3885: only re-render the component when message changed.
> Fix #3885: only re-render the component when message changed.

- Oqtane.Client/Modules/Controls/ActionDialog.razor
- Oqtane.Client/Modules/Controls/ActionLink.razor
- Oqtane.Client/Modules/Controls/Pager.razor
- Oqtane.Client/Modules/Controls/TabStrip.razor
ActionDialog and ActionLink now allow other icon sets whilst still adhering to the legacy "oi oi-" icon set. Pager added SearchBoxClass Class parameter to the Search div. TabStrip added a TabContentClass Class parameter to the tab content div.
> Oqtane controls updates

- Oqtane.Server/Components/App.razor
This pull request addresses an issue where non-ASCII characters were being introduced into HTTP client headers due to improper cookie date conversion. The date conversion was not taking into account culture and format, leading to non-ASCII characters being added on macOS between the time and the AM/PM part of the date.
The fix ensures that the cookie date is converted to text using a culture and format that preserves ASCII characters, thereby preventing non-ASCII characters from being added to the HTTP headers.
**Steps to Reproduce:**
1. Execute the project on a macOS and try to login.
2. An exception “Request headers must contain only ASCII characters.” will be thrown due to the character between the time and the AM/PM part of the date. Example cookie with problem: …
> Fix Cookie Date Conversion to Respect Culture and Format

- Oqtane.Client/Oqtane.Client.csproj
- Oqtane.Database.MySQL/Oqtane.Database.MySQL.csproj
- Oqtane.Database.PostgreSQL/Oqtane.Database.PostgreSQL.csproj
- Oqtane.Database.SqlServer/Oqtane.Database.SqlServer.csproj
- Oqtane.Database.Sqlite/Oqtane.Database.Sqlite.csproj
- Oqtane.Maui/Oqtane.Maui.csproj
- Oqtane.Package/Oqtane.Client.nuspec
- Oqtane.Package/Oqtane.Framework.nuspec
- Oqtane.Package/Oqtane.Server.nuspec
- Oqtane.Package/Oqtane.Shared.nuspec
- Oqtane.Package/Oqtane.Updater.nuspec
- Oqtane.Package/install.ps1
- Oqtane.Package/upgrade.ps1
- Oqtane.Server/Oqtane.Server.csproj
- Oqtane.Shared/Oqtane.Shared.csproj
- Oqtane.Updater/Oqtane.Updater.csproj
Prepares v5.2.0 Release and updates package dependencies.
Fixes #4324
Please review and provide feedback when time.  
Our POC for the new HTML Editor is on the front burner currently and we could use this update to ensure we are on the same when we test against latest framework repo.  We will help submit any discovered issues as we test as well if needed.
Progress on that project can be followed here:  https://github.com/ADefWebserver/ADefWebserver.Module.HtmlTextV2
> Fixes #4324: Updates package dependences and prepares v5.2.0 release

- Oqtane.Client/UI/ModuleInstance.placeholder.cs
- Oqtane.Client/UI/RenderModeBoundary.placeholder.cs
- Oqtane.Server/Components/_Placeholder.cs
> fix docfx build issues #4360

- Oqtane.Client/Modules/Controls/QuillJSTextEditor.razor
- Oqtane.Client/Resources/Modules/Controls/QuillJSTextEditor.resx
- Oqtane.Client/Resources/SharedResources.resx
- changed from button on toolbar to using a Settings tab
- fixed security for who should be allowed to manage Settings
- allowed Settings to be scoped to Site or Module
- provided support for optional static parameters
> QuillJSTextEditor setting improvements

- Oqtane.Client/Modules/Controls/QuillJSTextEditor.razor
The active tab in the Quill text editor was being set before loading settings. Therefore, the active tab was Raw even if raw html is not allowed.
> fix: set Rich active tab for Quill text editor

- Oqtane.Server/Infrastructure/SiteTemplates/AdminSiteTemplate.cs
When logged in with an account only in the Registered Users role, the page under the URL "admin/pages" does not show a 404 page. Instead it stays blank. This behavior is different to all the other admin pages, and this PR fixes that.
> Fix admin/pages not showing 404 for unauthorized users

- Oqtane.Server/Components/App.razor
- Oqtane.Server/Startup.cs
Fixes #4492 
Sets options on cookies for samesite, secure and httponly for Culture and Visitor cookies to lax (default) in order to remove browser warnings.
Visitor cookie adds these options:
```
SameSite = Microsoft.AspNetCore.Http.SameSiteMode.Lax, // Set SameSite attribute
Secure = true, // Ensure the cookie is only sent over HTTPS
HttpOnly = true // Optional: Helps mitigate XSS attacks
```
Culture cookie adds these options:
```
Expires = DateTimeOffset.UtcNow.AddYears(1),
SameSite = Microsoft.AspNetCore.Http.SameSiteMode.Lax, // Set SameSite attribute
Secure = true, // Ensure the cookie is only sent over HTTPS
HttpOnly = true // Optional: Helps mitigate XSS attacks
```
Some added cookie options such as Expires/Secure/HttpOnly may need reviewed/adjusted or maybe this is not the fix but …
> Fix #4492: Updates Culture and Visitor cookies to use "Lax" SameSite and Secure Cookie Options

- Oqtane.Client/Resources/SharedResources.resx
it will make search settings translatable
> search settings translation entry

- .gitignore
- Oqtane.Server/wwwroot/Modules/Templates/External/Client/Startup/ClientStartup.cs
- Oqtane.Server/wwwroot/Modules/Templates/External/Server/Startup/ServerStartup.cs
PR #4541 was not valid as it did not actually include the necessary changes to resolve issue #4537 - this was because the gitignore file was excluding files which should have been included. This PR fixes the gitignore and merges the default module template files which were supposed to be committed in #4541
> fix #4562 - module template issue caused by gitignore

- Oqtane.Client/Modules/Controls/ActionDialog.razor
It was just a matter of the order in which the _openText variable is set.
This PR fixes https://github.com/oqtane/oqtane.framework/issues/4586.
> Fix IconOnly not working

- Oqtane.Server/Controllers/FileController.cs
- Oqtane.Server/Extensions/OqtaneServiceCollectionExtensions.cs
- Oqtane.Server/Pages/Files.cshtml.cs
- Oqtane.Server/Services/ImageService.cs
- Oqtane.Shared/Interfaces/IImageService.cs
- Extracts the image creation into a service
- Refactors Files Page GET action for better readability and cyclomatic complexity
- Allows changing the image encoding: webp or png (default)
- Includes all parameters in the Etag calculation
Related to #4692
> Image Resizing and Format via QueryString in Files Page (enhances #4692)

- Oqtane.Client/Modules/Admin/Users/Index.razor
Fixes #4758
adds scroll to top as a `finally` part of the `try/catch` block
> Scroll to top after saving settings - Fixes #4758

- Oqtane.Maui/wwwroot/js/interop.js
- Oqtane.Server/wwwroot/js/interop.js
Fixes #4762
Adds logic ScrollTo interop.js method detecting if method is executed inside a `class=".modal"` for places like the admin modal popups.
This allows the ScrollToTop function to work properly inside areas like the admin\pages\add.razor popup modal
> Fixes #4762: Adds logic ScrollTo interop.js method detecting if method is executed inside a modal

- Oqtane.Client/Themes/Controls/Theme/Search.razor
The search button in Search component does not have the aria-label.
> Fix: Accesibility issue for Search Button

- Oqtane.Client/Modules/Admin/Search/Index.razor
"Search_Enabled" in the settings was being saved as Private this meant that unauthorized users could not access this value.
> Fix: for Disabling search does not hide search icon #4824

- Oqtane.Client/Modules/Admin/Modules/Settings.razor
- Oqtane.Client/Modules/Admin/Pages/Add.razor
- Oqtane.Client/Modules/Admin/Pages/Edit.razor
- Oqtane.Client/Modules/Controls/QuillJSTextEditor.razor
- Oqtane.Client/Modules/Controls/TabPanel.razor
- Oqtane.Client/Modules/Controls/TabStrip.razor
Fix for TabPanel is not updating the UI. [#4778](https://github.com/oqtane/oqtane.framework/issues/4778) [#4828](https://github.com/oqtane/oqtane.framework/issues/4828)
> Rework for Tabstrip regression issue

- Oqtane.Server/Infrastructure/Middleware/JwtMiddleware.cs
Resolves issue where user was always returned as null.
> Fix #4885 - Pass userid as int to GetUser for JWT authentication

- Oqtane.Client/Themes/Controls/Theme/ControlPanel.razor
- Oqtane.Client/Themes/Controls/Theme/ControlPanelInteractive.razor
This enhancement addresses issue #4883 by introducing a ShowEditMode parameter to the ControlPanel component. This allows theme developers to hide the Edit Mode toggle button when desired.
•	Added a new `ShowEditMode` parameter to `ControlPanel.razor` with a default value of `true` to maintain existing behavior.
•	Updated the `ControlPanel` logic to conditionally display the Edit Mode toggle button based on the `ShowEditMode` value.
Extensive testing was conducted to ensure this change works as intended across various scenarios.
- **Themes Tested**: `Default` themes of **Oqtane** and **Blazor**.
- **Users**: Anonymous and Admin.
- **Render Combinations**:
- Static, Server
- Static, Client
- Static, Auto
- Interactive, Server
- Interactive, Client
- Interactive, Auto
- **Results**:
- …
> Add ShowEditMode parameter to ControlPanel to allow hiding the Edit Mode toggle button

- Oqtane.Server/wwwroot/Modules/Templates/External/Package/[Owner].Module.[Module].Package.csproj
- Oqtane.Server/wwwroot/Modules/Templates/External/Package/[Owner].Module.[Module].nuspec
- Oqtane.Server/wwwroot/Modules/Templates/External/Package/debug.cmd
- Oqtane.Server/wwwroot/Modules/Templates/External/Package/debug.sh
- Oqtane.Server/wwwroot/Modules/Templates/External/Package/release.cmd
- Oqtane.Server/wwwroot/Modules/Templates/External/Package/release.sh
- Oqtane.Server/wwwroot/Themes/Templates/External/Package/[Owner].Theme.[Theme].Package.csproj
- Oqtane.Server/wwwroot/Themes/Templates/External/Package/[Owner].Theme.[Theme].nuspec
- Oqtane.Server/wwwroot/Themes/Templates/External/Package/debug.cmd
- Oqtane.Server/wwwroot/Themes/Templates/External/Package/debug.sh
- Oqtane.Server/wwwroot/Themes/Templates/External/Package/release.cmd
- Oqtane.Server/wwwroot/Themes/Templates/External/Package/release.sh
This PR updates our debug scripts (both .cmd and .sh) to dynamically use the current TargetFramework passed from the build process. This change improves flexibility and future-proofs our build process for different .NET versions.
- Modified build events to pass $(TargetFramework) to debug scripts
- Updated debug.cmd to accept and use the TargetFramework parameter
- Updated debug.sh to accept and use the TargetFramework parameter
- Replaced hardcoded framework versions (e.g., net9.0) with the dynamic TargetFramework variable in file paths
1. Build the project with different TargetFramework settings
2. Verify that the correct files are copied to the appropriate directories based on the current TargetFramework
This change affects the build process but should not impact runtime behavior. It …
> Implement Dynamic TargetFramework in Debug Scripts #4897

- Oqtane.Client/Modules/Admin/UserProfile/Index.razor
- Oqtane.Client/Modules/Admin/Users/Add.razor
- Oqtane.Client/Modules/Admin/Users/Edit.razor
This update applies the maxlength attribute fix to all input and textarea elements. The maxlength attribute will only be added if p.MaxLength is greater than 0, allowing unlimited characters when it's 0 or less.
> FIX for #4906 Profile Field does not allow max length

- Oqtane.Server/wwwroot/Modules/Templates/External/Package/[Owner].Module.[Module].Package.csproj
- Oqtane.Server/wwwroot/Modules/Templates/External/Package/[Owner].Module.[Module].nuspec
- Oqtane.Server/wwwroot/Modules/Templates/External/Package/debug.cmd
- Oqtane.Server/wwwroot/Modules/Templates/External/Package/debug.sh
- Oqtane.Server/wwwroot/Modules/Templates/External/Package/release.cmd
- Oqtane.Server/wwwroot/Modules/Templates/External/Package/release.sh
- Oqtane.Server/wwwroot/Themes/Templates/External/Package/[Owner].Theme.[Theme].Package.csproj
- Oqtane.Server/wwwroot/Themes/Templates/External/Package/[Owner].Theme.[Theme].nuspec
- Oqtane.Server/wwwroot/Themes/Templates/External/Package/debug.cmd
- Oqtane.Server/wwwroot/Themes/Templates/External/Package/debug.sh
- Oqtane.Server/wwwroot/Themes/Templates/External/Package/release.cmd
- Oqtane.Server/wwwroot/Themes/Templates/External/Package/release.sh
This pull request introduces a dynamic ProjectName parameter across our build process, enhancing flexibility and reducing hardcoding in our module and theme development workflow. The changes affect the project file, NuSpec file, command scripts.
> Implement Dynamic ProjectName Parameter Across Build Process

- Oqtane.Client/Modules/Admin/UserProfile/Index.razor
- Oqtane.Client/Modules/Admin/Users/Edit.razor
This pull request updates the User Profile implementation to utilize the existing User Settings object on the user object. While the current implementation is functional, this change offers several benefits: Improved code consistency
Better guidance for developers accessing User Settings Alignment with the framework's best practices.
**Key Changes**
Refactored User Profile to leverage the User Settings object
Updated relevant documentation and comments
**Motivation**
This update addresses the issue raised in #4905 regarding custom properties of the current user's profile. By utilizing the User Settings object, we provide a more standardized approach to handling user-specific data.
> User Profile Update: Utilizing User Settings Object

- Oqtane.Client/Modules/Admin/Pages/Add.razor
- Oqtane.Client/Modules/Admin/Pages/Edit.razor
- Oqtane.Client/Resources/Modules/Admin/Pages/Add.resx
- Oqtane.Client/Resources/Modules/Admin/Pages/Edit.resx
Fixes #4781: 
- Adds Edit + Add page ScrollToTopPage() on error messages.
> Fixes #4781: Adds Edit + Add Page ScrollToTopPage() On Settings Tab Form Error Messages

- Oqtane.Shared/Oqtane.Shared.csproj
This ensures an older version of System.Text.Json is not pulled in via a transitive dependency
> add back System.Text.Json to Shared project (#4929)

- Oqtane.Server/Pages/Files.cshtml.cs
Reformated images were still displaying the original format in the Content-Type response headers.
> FIX: File server MimeType not updated after image conversion

- Oqtane.Client/Modules/Controls/ActionDialog.razor
This PR introduces a new private method GetButtonSize() to enhance the consistency of button sizing within our UI. The method specifically checks for the presence of the "btn-sm" class in the Action Button's class list and applies the same sizing to the Cancel Button if found.
> Update ActionDialog Add method to ensure consistent button sizing

- Oqtane.Server/Startup.cs
- Oqtane.Server/appsettings.json
This PR addresses issue #5005 by adding the Cache-Control header for static file responses. This enhancement will allow browsers to cache static assets such as images, JavaScript, and CSS, improving performance by reducing the number of network requests on subsequent visits. The change is aimed at improving Lighthouse performance metrics for the application.
Testing:
Changes have been tested locally to confirm the Cache-Control headers are being correctly applied to static files.
Performance testing has shown an improvement in load times when the caching headers are applied.
Note:
Since this is my first PR, please let me know if there are any suggestions for improvements if I have missed anything or if I have done it totally wrong!!. I'm open to feedback!
> Fixes #5005: Add Browser Caching for Static Assets

- Oqtane.Server/wwwroot/js/interop.js
> The requests in each file are processed sequentially (one at a time), but the files itself are processed in parallel. Therefore, with 40 1MB files you would get 40 simultaneous requests.
Solved by this PR, fixes #5058
> fix #5058: ensure sequential file and chunk uploads to avoid overload

- Oqtane.Client/Modules/Controls/FileManager.razor
- Oqtane.Client/UI/Interop.cs
Fixes #5074 by generating a cancellation token to override the default JSRuntime timeout
> fix #5074: generate cancellation token for file upload

- Oqtane.Client/Extensions/OqtaneServiceCollectionExtensions.cs
- Oqtane.Client/Modules/Admin/Site/Index.razor
- Oqtane.Client/Resources/Modules/Admin/Site/Index.resx
- Oqtane.Client/Services/CacheService.cs
- Oqtane.Client/Services/Interfaces/ICacheService.cs
- Oqtane.Server/Controllers/CacheController.cs
- Oqtane.Server/Extensions/OqtaneServiceCollectionExtensions.cs
- Oqtane.Server/Pages/Sitemap.cshtml.cs
- Oqtane.Server/Services/CacheService.cs
- Oqtane.Server/Startup.cs
- Oqtane.Shared/Shared/Constants.cs
Resolves #4899 by adding output cache to Oqtane and caching the sitemap response. 
It implements a short-lifed 5 minute cache that can be manually cleared through site settings with a new CacheService.
> resolves #4899: output cache for sitemap

- Oqtane.Server/Pages/Files.cshtml.cs
- Oqtane.Shared/Shared/Utilities.cs
Implements some optimizations for the /files server:
- Early return when 404 or 304, before evaluating query string
- Improves ETag compute by always including the ModifiedOn property and using MD5 to reduce probability of collisions (important when using CDNs)
> Files server optimization

- Oqtane.Server/Infrastructure/Middleware/TenantMiddleware.cs
- Oqtane.Server/Startup.cs
Note - this could be a breaking change for some third party modules which rely on the current location where Configure is executed.
> fix #5229 - move IServerStartup.Configure execution until later so that it is possible to register custom endpoints

- Oqtane.Client/Modules/ModuleBase.cs
The _urlparametersstate variable is not initialized so in GetUrlParameters it causes a crash
> GetUrlParameters crash

- Oqtane.Shared/Modules/HtmlText/Models/HtmlText.cs
Fixes #5280
This PR removes the following unused using directives from the HtmlText.cs file in the Oqtane HtmlText module to improve code clarity and reduce potential build overhead:
- using System.ComponentModel.DataAnnotations.Schema;
- using System;
> Fixes #5280: Remove Unused Namespaces from HtmlText.cs in HtmlText Module

- Oqtane.Client/Oqtane.Client.csproj
- Oqtane.Database.MySQL/Oqtane.Database.MySQL.csproj
- Oqtane.Database.PostgreSQL/Oqtane.Database.PostgreSQL.csproj
- Oqtane.Database.SqlServer/Oqtane.Database.SqlServer.csproj
- Oqtane.Database.Sqlite/Oqtane.Database.Sqlite.csproj
- Oqtane.Maui/Oqtane.Maui.csproj
- Oqtane.Package/Oqtane.Client.nuspec
- Oqtane.Package/Oqtane.Framework.nuspec
- Oqtane.Package/Oqtane.Server.nuspec
- Oqtane.Package/Oqtane.Shared.nuspec
- Oqtane.Package/Oqtane.Updater.nuspec
- Oqtane.Package/install.ps1
- Oqtane.Package/upgrade.ps1
- Oqtane.Server/Oqtane.Server.csproj
- Oqtane.Shared/Oqtane.Shared.csproj
- Oqtane.Updater/Oqtane.Updater.csproj
Fixes #5267 
Since it was decided to put out another maintenance release for 6.1 I will close the other PR for the 6.2.0 version update and update the issue relating.
This PR updates the dependencies and version of Oqtane Framework to 6.1.3.
> Fixes #5267: Updates Project Dependencies and Version to 6.1.3

- Oqtane.Client/Themes/Controls/Theme/CookieConsent.razor
Fixes #5352 with an early return in the CookieConsent control initialization method if cookie consent is not enabled.
> fix #5352: remove requests to cookie consent service when not enabled

- Oqtane.Client/Modules/Admin/Jobs/Edit.razor
- Oqtane.Client/Modules/ModuleBase.cs
This PR addresses an issue where null date/time values could cause exceptions when processing job scheduling. 
**Changes Made**:
- Added proper null checks for _startDate, _startTime, _endDate, _endTime, _nextDate, and _nextTime
- Improved parsing safety for _retentionHistory using int.TryParse()
- Added validation to fail early with meaningful error messages
**Impact**:
Prevents NullReferenceException and InvalidOperationException when date/time fields are missing
> Fix for Scheduled Jobs UI #5354

- Oqtane.Server/Infrastructure/Jobs/NotificationJob.cs
- Oqtane.Server/Oqtane.Server.csproj
Replaces System.Net.Mail with the MailKit library to send emails in the NotificationJob.
The only question I have is related to the UseSSL option. I believe it can be removed from the SiteSettings UI as the connect method should use MailKit.Security.SecureSocketOptions.Auto, although I'm not 100% sure of the implications
> feat: replace System.Net.Mail with MailKit (#5372)

- Oqtane.Maui/wwwroot/css/app.css
- Oqtane.Server/wwwroot/css/app.css
Fixes: #5164
- Updated `app.css` in both `Oqtane.Server` and `Oqtane.Maui` to set:
`.app-moduleactions .dropdown-menu.show { z-index: 9000;}`
- Ensures dropdowns reliably display above other elements
- z-index of **9999** to match the other top z-index styles set in the app.css files.
>  [FIX] #5164 - Set z-index for .dropdown-menu in .app-moduleactions

- Oqtane.Server/Oqtane.Server.csproj
- azuredeploy.json
Updates link to v6.2.0 in azuredeploy.json and updates the Oqtane.Server project dependencies for Swashbuckle.AspNetCore plus SQLitePCLRaw.bundle_e_sqlite3 to latest releases.
> Update v6.2.0 azure deploy and Oqtane.Server project dependencies

- Oqtane.Server/Infrastructure/Jobs/NotificationJob.cs
- Oqtane.Server/Repository/NotificationRepository.cs
MailboxAddress.TryParse() seems to use different logic than the MailboxAddress() constructor and as a result, email addresses which pass the TryParse() validation will sometimes throw a parsing exception when creating a new MailboxAddress() object. This behavior is different than System.Net.Mail and did not have exception handling, resulting in the job terminating prematurely.,
> fix issues with NotificationJob related to MailKit behavior
